import {
  App,
  Notice,
  Plugin,
  PluginSettingTab,
  Setting,
  TFile,
  requestUrl
} from 'obsidian';
import {
  BlipPack,
  LocalCli,
  buildPrompt,
  detectBinary,
  formatDate,
  generateFallback,
  parsePackFromText
} from './lib';

type AiProvider = 'local-cli' | 'openai' | 'fallback';

interface BlipResurfacerSettings {
  maxDailyResurface: number;
  aiProvider: AiProvider;
  localCli: LocalCli;
  strictLocalAi: boolean;
  openaiApiKey: string;
  openaiModel: string;
  userContext: string;
}

const DEFAULT_SETTINGS: BlipResurfacerSettings = {
  maxDailyResurface: 3,
  aiProvider: 'local-cli',
  localCli: 'claude',
  strictLocalAi: true,
  openaiApiKey: '',
  openaiModel: 'gpt-4o-mini',
  userContext:
    'User is an experienced backend engineer. Prefer concrete, small next steps and practical mini-POCs.'
};

export default class BlipResurfacerPlugin extends Plugin {
  settings: BlipResurfacerSettings = DEFAULT_SETTINGS;
  private binaryCache: Map<string, string> = new Map();

  async onload() {
    await this.loadSettings();

    this.addCommand({
      id: 'resurface-blips-now',
      name: 'Resurface current blip',
      callback: async () => {
        const name = await this.resurfaceCurrentBlip();
        if (!name) new Notice('Blip Resurfacer: no blip file found.');
        else new Notice(`Blip Resurfacer: updated "${name}"`);
      }
    });

    this.addCommand({
      id: 'test-local-ai-backend',
      name: 'Test local AI backend (Codex/Claude)',
      callback: async () => {
        try {
          const pack = await this.generateViaLocalCli(
            'Backend connectivity test',
            'Create one insight and two practical steps about learning Kafka over TCP.'
          );
          new Notice(
            `Local AI OK (${this.settings.localCli}). Insight: ${pack.insight.slice(0, 80)}...`
          );
        } catch (e) {
          new Notice(
            `Local AI failed (${this.settings.localCli}): ${String((e as Error)?.message || e).slice(0, 140)}`
          );
        }
      }
    });

    this.addSettingTab(new BlipResurfacerSettingTab(this.app, this));
  }

  async loadSettings() {
    const saved = await this.loadData();
    const loaded = Object.assign({}, DEFAULT_SETTINGS, saved) as BlipResurfacerSettings & {
      aiEnabled?: boolean;
    };

    // Legacy migration from v0.1.0 aiEnabled key
    if (typeof loaded.aiEnabled === 'boolean') {
      if (!loaded.aiEnabled) loaded.aiProvider = 'fallback';
      else if (loaded.aiProvider === 'fallback') loaded.aiProvider = 'local-cli';
    }

    this.settings = loaded;
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }

  /**
   * Returns the file to resurface: the active file if it's a blip,
   * otherwise the oldest (least recently reviewed) blip in the vault.
   */
  private async pickBlipFile(): Promise<TFile | null> {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile && this.isBlipFile(activeFile)) {
      return activeFile;
    }
    const blips = await this.getBlipFiles();
    return blips[0] ?? null;
  }

  private isBlipFile(file: TFile): boolean {
    const fm = this.app.metadataCache.getFileCache(file)?.frontmatter as
      | Record<string, unknown>
      | undefined;
    return !!fm && String(fm.type ?? '').toLowerCase() === 'blip';
  }

  private async getBlipFiles(): Promise<TFile[]> {
    return this.app.vault.getMarkdownFiles()
      .filter((file) => this.isBlipFile(file))
      .sort((a, b) => a.stat.mtime - b.stat.mtime);
  }

  /** Resurface current blip: active file if it's a blip, else oldest unreviewed blip. */
  async resurfaceCurrentBlip(): Promise<string | null> {
    const file = await this.pickBlipFile();
    if (!file) return null;
    await this.resurfaceFile(file);
    return file.basename;
  }

  private async resurfaceFile(file: TFile): Promise<void> {
    const text = await this.app.vault.read(file);
    const pack = await this.generateBlipPack(file.basename, text);
    await this.appendBlipUpdate(file, pack);
  }

  private async appendBlipUpdate(file: TFile, pack: BlipPack) {
    const dateStr = formatDate(new Date());
    const sectionHeader = '## Blip updates (Clawd)';

    const entry = [
      `### ${dateStr}`,
      `- Generated by: ${this.settings.aiProvider === 'local-cli' ? this.settings.localCli : this.settings.aiProvider}`,
      `- Insight: ${pack.insight}`,
      `- Next quality steps:`,
      ...pack.nextSteps.map((s) => `  - ${s}`),
      `- Reminder: ${pack.reminder}`,
      ''
    ].join('\n');

    const content = await this.app.vault.read(file);

    if (content.includes(sectionHeader)) {
      await this.app.vault.modify(file, `${content.trimEnd()}\n\n${entry}`);
      return;
    }

    await this.app.vault.modify(file, `${content.trimEnd()}\n\n${sectionHeader}\n\n${entry}`);
  }

  private async generateBlipPack(title: string, noteContent: string): Promise<BlipPack> {
    if (this.settings.aiProvider === 'local-cli') {
      try {
        return await this.generateViaLocalCli(title, noteContent);
      } catch (e) {
        const msg = String((e as Error)?.message || e);
        console.error('Blip Resurfacer local CLI failed', e);
        new Notice(
          `Blip Resurfacer: local ${this.settings.localCli} failed (${msg.slice(0, 120)})`
        );
        if (this.settings.strictLocalAi) throw e;
      }
    }

    if (this.settings.aiProvider === 'openai' && this.settings.openaiApiKey.trim()) {
      try {
        return await this.generateViaOpenAI(title, noteContent);
      } catch (e) {
        console.error('Blip Resurfacer OpenAI failed, using fallback', e);
      }
    }

    return generateFallback(title, noteContent);
  }

  private async generateViaLocalCli(title: string, noteContent: string): Promise<BlipPack> {
    const prompt = buildPrompt(this.settings.userContext, title, noteContent);
    const vaultPath = this.app.vault.adapter.getBasePath();
    const req = this.nodeRequire();
    const fs = req('fs') as typeof import('fs');

    let stdout = '';

    if (this.settings.localCli === 'codex') {
      const os = req('os') as typeof import('os');
      const codexBin = await this.resolveBin('codex');
      const outPath = `${os.tmpdir()}/blip-resurfacer-${Date.now()}.json`;
      const schemaPath = `${os.tmpdir()}/blip-resurfacer-schema-${Date.now()}.json`;

      fs.writeFileSync(
        schemaPath,
        JSON.stringify({
          type: 'object',
          additionalProperties: false,
          required: ['insight', 'nextSteps', 'reminder'],
          properties: {
            insight: { type: 'string' },
            nextSteps: { type: 'array', minItems: 2, maxItems: 3, items: { type: 'string' } },
            reminder: { type: 'string' }
          }
        })
      );

      const args = [
        'exec',
        '--skip-git-repo-check',
        '--output-schema',
        schemaPath,
        '-C',
        vaultPath,
        '--output-last-message',
        outPath,
        '-'
      ];

      const nodeBin = await this.resolveBin('node');
      await this.runCommand(nodeBin, [codexBin, ...args], prompt, vaultPath);
      stdout = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : '';
      if (fs.existsSync(outPath)) fs.unlinkSync(outPath);
      if (fs.existsSync(schemaPath)) fs.unlinkSync(schemaPath);
    } else {
      const claudeBin = await this.resolveBin('claude');
      stdout = await this.runCommand(claudeBin, ['-p', '--output-format', 'text', prompt], undefined, vaultPath);
    }

    return parsePackFromText(stdout);
  }

  private async generateViaOpenAI(title: string, noteContent: string): Promise<BlipPack> {
    const prompt = buildPrompt(this.settings.userContext, title, noteContent);

    const res = await requestUrl({
      url: 'https://api.openai.com/v1/chat/completions',
      method: 'POST',
      headers: {
        Authorization: `Bearer ${this.settings.openaiApiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: this.settings.openaiModel,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.2,
        response_format: { type: 'json_object' }
      })
    });

    const raw = res.json?.choices?.[0]?.message?.content ?? '{}';
    return parsePackFromText(raw);
  }

  /** Resolve a binary once and cache for the lifetime of the plugin. */
  private async resolveBin(name: string): Promise<string> {
    if (!this.binaryCache.has(name)) {
      const req = this.nodeRequire();
      const cp = req('child_process') as typeof import('child_process');
      const home = process.env.HOME ?? '';
      const found = await detectBinary(name, (cmd) =>
        new Promise((res, rej) =>
          cp.exec(cmd, (err, stdout) => (err ? rej(err) : res(stdout)))
        ),
        home
      );
      this.binaryCache.set(name, found);
    }
    return this.binaryCache.get(name)!;
  }

  private async runCommand(
    command: string,
    args: string[],
    stdinText?: string,
    cwd?: string
  ): Promise<string> {
    const req = this.nodeRequire();
    const cp = req('child_process') as typeof import('child_process');

    // Strip CLAUDECODE so nested claude CLI invocations don't refuse to launch.
    const env = { ...process.env };
    delete env['CLAUDECODE'];

    return new Promise((resolve, reject) => {
      const child = cp.spawn(command, args, { cwd, shell: false, env });

      let stdout = '';
      let stderr = '';

      child.stdout?.on('data', (d: Buffer) => (stdout += d.toString('utf8')));
      child.stderr?.on('data', (d: Buffer) => (stderr += d.toString('utf8')));
      child.on('error', (err: NodeJS.ErrnoException) => {
        if (err?.code === 'ENOENT') {
          reject(new Error(`${command} not found (ENOENT). Check that ${command} is installed.`));
          return;
        }
        reject(err);
      });
      child.on('close', (code) => {
        if (code === 0) resolve(stdout.trim());
        else reject(new Error(`${command} exited ${code}: ${stderr || stdout}`));
      });

      if (stdinText && child.stdin) child.stdin.write(stdinText);
      child.stdin?.end();
    });
  }

  private nodeRequire() {
    const req = (window as unknown as { require?: NodeRequire }).require;
    if (!req) {
      throw new Error('Node require() unavailable. Local CLI mode needs desktop Obsidian.');
    }
    return req;
  }
}

class BlipResurfacerSettingTab extends PluginSettingTab {
  plugin: BlipResurfacerPlugin;

  constructor(app: App, plugin: BlipResurfacerPlugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display(): void {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl('h2', { text: 'Blip Resurfacer' });

    new Setting(containerEl)
      .setName('Max daily resurfaced blips')
      .setDesc('How many blips the scheduled cron job resurfaces per day')
      .addText((text) =>
        text
          .setValue(String(this.plugin.settings.maxDailyResurface))
          .onChange(async (value) => {
            const n = Number(value);
            if (!Number.isNaN(n) && n > 0) {
              this.plugin.settings.maxDailyResurface = n;
              await this.plugin.saveSettings();
            }
          })
      );

    new Setting(containerEl)
      .setName('AI provider')
      .setDesc('Local CLI uses Codex or Claude Code installed on this machine.')
      .addDropdown((dd) =>
        dd
          .addOption('local-cli', 'Local CLI (Codex / Claude)')
          .addOption('openai', 'OpenAI API')
          .addOption('fallback', 'Fallback only (rule-based)')
          .setValue(this.plugin.settings.aiProvider)
          .onChange(async (value: AiProvider) => {
            this.plugin.settings.aiProvider = value;
            await this.plugin.saveSettings();
            this.display();
          })
      );

    if (this.plugin.settings.aiProvider === 'local-cli') {
      new Setting(containerEl)
        .setName('Local CLI')
        .setDesc('CLI binary to call. The plugin auto-detects the path via which.')
        .addDropdown((dd) =>
          dd
            .addOption('claude', 'Claude Code')
            .addOption('codex', 'Codex')
            .setValue(this.plugin.settings.localCli)
            .onChange(async (value: LocalCli) => {
              this.plugin.settings.localCli = value;
              await this.plugin.saveSettings();
              this.display();
            })
        );

      new Setting(containerEl)
        .setName('Strict local AI mode')
        .setDesc('Stop the run if the local CLI fails instead of falling back to rule-based output')
        .addToggle((toggle) =>
          toggle
            .setValue(this.plugin.settings.strictLocalAi)
            .onChange(async (value) => {
              this.plugin.settings.strictLocalAi = value;
              await this.plugin.saveSettings();
            })
        );
    }

    if (this.plugin.settings.aiProvider === 'openai') {
      new Setting(containerEl)
        .setName('OpenAI API key')
        .addText((text) =>
          text
            .setPlaceholder('sk-...')
            .setValue(this.plugin.settings.openaiApiKey)
            .onChange(async (value) => {
              this.plugin.settings.openaiApiKey = value.trim();
              await this.plugin.saveSettings();
            })
        );

      new Setting(containerEl)
        .setName('OpenAI model')
        .addText((text) =>
          text
            .setValue(this.plugin.settings.openaiModel)
            .onChange(async (value) => {
              this.plugin.settings.openaiModel = value.trim() || 'gpt-4o-mini';
              await this.plugin.saveSettings();
            })
        );
    }

    new Setting(containerEl)
      .setName('User context')
      .setDesc('Appended to every AI prompt to tailor next steps')
      .addTextArea((text) =>
        text
          .setValue(this.plugin.settings.userContext)
          .onChange(async (value) => {
            this.plugin.settings.userContext = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Resurface current blip')
      .setDesc(
        'Resurfaces the currently open blip note, or the oldest unreviewed blip if none is open'
      )
      .addButton((btn) =>
        btn.setButtonText('Run now').onClick(async () => {
          const name = await this.plugin.resurfaceCurrentBlip();
          if (!name) new Notice('Blip Resurfacer: no blip file found.');
          else new Notice(`Blip Resurfacer: updated "${name}"`);
        })
      );
  }
}
