"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BlipResurfacerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  maxDailyResurface: 2,
  aiProvider: "local-cli",
  localCli: "codex",
  strictLocalAi: true,
  codexModel: "gpt-5-codex",
  claudeModel: "sonnet",
  codexPath: "/Users/parashuram/.npm-global/bin/codex",
  claudePath: "/Users/parashuram/.local/bin/claude",
  nodePath: "/opt/homebrew/bin/node",
  openaiApiKey: "",
  openaiModel: "gpt-4o-mini",
  userContext: "User is an experienced backend engineer. Prefer concrete, small next steps and practical mini-POCs."
};
var BlipResurfacerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "resurface-blips-now",
      name: "Resurface blips now",
      callback: async () => {
        const count = await this.resurfaceNow();
        new import_obsidian.Notice(`Blip Resurfacer: updated ${count} blip(s)`);
      }
    });
    this.addCommand({
      id: "test-local-ai-backend",
      name: "Test local AI backend (Codex/Claude)",
      callback: async () => {
        try {
          const pack = await this.generateViaLocalCli(
            "Backend connectivity test",
            "Create one insight and two practical steps about learning Kafka over TCP."
          );
          new import_obsidian.Notice(`Local AI OK (${this.settings.localCli}). Insight: ${pack.insight.slice(0, 80)}...`);
        } catch (e) {
          new import_obsidian.Notice(`Local AI failed (${this.settings.localCli}): ${String(e?.message || e).slice(0, 140)}`);
        }
      }
    });
    this.addSettingTab(new BlipResurfacerSettingTab(this.app, this));
  }
  async loadSettings() {
    const loaded = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (typeof loaded.aiEnabled === "boolean") {
      if (!loaded.aiEnabled) loaded.aiProvider = "fallback";
      else if (loaded.aiProvider === "fallback") loaded.aiProvider = "local-cli";
    }
    if (!loaded.codexModel?.trim() || loaded.codexModel.includes("gpt-5.3-codex")) {
      loaded.codexModel = "gpt-5-codex";
    }
    if (!loaded.claudeModel?.trim()) {
      loaded.claudeModel = "sonnet";
    }
    if (!loaded.codexPath?.trim()) {
      loaded.codexPath = "/Users/parashuram/.npm-global/bin/codex";
    }
    if (!loaded.claudePath?.trim()) {
      loaded.claudePath = "/Users/parashuram/.local/bin/claude";
    }
    if (!loaded.nodePath?.trim()) {
      loaded.nodePath = "/opt/homebrew/bin/node";
    }
    this.settings = loaded;
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async resurfaceNow() {
    const blips = await this.getBlipFiles();
    if (!blips.length) {
      new import_obsidian.Notice("No notes with type: blip found.");
      return 0;
    }
    const selected = blips.slice(0, Math.max(1, this.settings.maxDailyResurface));
    for (const file of selected) {
      const text = await this.app.vault.read(file);
      const pack = await this.generateBlipPack(file.basename, text);
      await this.appendBlipUpdate(file, pack);
    }
    return selected.length;
  }
  async getBlipFiles() {
    return this.app.vault.getMarkdownFiles().filter((file) => {
      const cache = this.app.metadataCache.getFileCache(file);
      const fm = cache?.frontmatter;
      return fm && String(fm.type ?? "").toLowerCase() === "blip";
    }).sort((a, b) => a.stat.mtime - b.stat.mtime);
  }
  async appendBlipUpdate(file, pack) {
    const dateStr = this.formatDate(/* @__PURE__ */ new Date());
    const sectionHeader = "## Blip updates (Clawd)";
    const entry = [
      `### ${dateStr}`,
      `- Generated by: ${this.settings.aiProvider === "local-cli" ? this.settings.localCli : this.settings.aiProvider}`,
      `- Insight: ${pack.insight}`,
      `- Next quality steps:`,
      ...pack.nextSteps.map((s) => `  - ${s}`),
      `- Reminder: ${pack.reminder}`,
      ""
    ].join("\n");
    const content = await this.app.vault.read(file);
    if (content.includes(sectionHeader)) {
      await this.app.vault.modify(file, `${content.trimEnd()}

${entry}`);
      return;
    }
    const updated = `${content.trimEnd()}

${sectionHeader}

${entry}`;
    await this.app.vault.modify(file, updated);
  }
  async generateBlipPack(title, noteContent) {
    if (this.settings.aiProvider === "local-cli") {
      try {
        return await this.generateViaLocalCli(title, noteContent);
      } catch (e) {
        const msg = String(e?.message || e);
        console.error("Blip Resurfacer local CLI failed", e);
        new import_obsidian.Notice(`Blip Resurfacer: local ${this.settings.localCli} failed (${msg.slice(0, 120)})`);
        if (this.settings.strictLocalAi) {
          throw e;
        }
      }
    }
    if (this.settings.aiProvider === "openai" && this.settings.openaiApiKey.trim()) {
      try {
        return await this.generateViaOpenAI(title, noteContent);
      } catch (e) {
        console.error("Blip Resurfacer OpenAI failed, using fallback", e);
      }
    }
    return this.generateFallback(title, noteContent);
  }
  buildPrompt(title, noteContent) {
    return `You help resurface personal Obsidian blips in-place.

Context:
- ${this.settings.userContext}
- Keep output practical, small, and execution-first.
- Output must be valid JSON only.

Blip title: ${title}
Blip content excerpt:
${noteContent.slice(0, 3500)}

Return JSON exactly with keys:
{
  "insight": "string (max 2 lines)",
  "nextSteps": ["2-3 concrete steps"],
  "reminder": "one short reminder"
}`;
  }
  async generateViaLocalCli(title, noteContent) {
    const prompt = this.buildPrompt(title, noteContent);
    const vaultPath = this.app.vault.adapter.getBasePath();
    let stdout = "";
    if (this.settings.localCli === "codex") {
      const req = this.nodeRequire();
      const fs = req("fs");
      const os = req("os");
      const path = req("path");
      const codexBin = this.resolveLocalCliBinary("codex", this.settings.codexPath);
      const outPath = path.join(os.tmpdir(), `blip-resurfacer-${Date.now()}.json`);
      const schemaPath = path.join(os.tmpdir(), `blip-resurfacer-schema-${Date.now()}.json`);
      fs.writeFileSync(
        schemaPath,
        JSON.stringify({
          type: "object",
          additionalProperties: false,
          required: ["insight", "nextSteps", "reminder"],
          properties: {
            insight: { type: "string" },
            nextSteps: { type: "array", minItems: 2, maxItems: 3, items: { type: "string" } },
            reminder: { type: "string" }
          }
        })
      );
      const args = [
        "exec",
        "--skip-git-repo-check",
        "--output-schema",
        schemaPath,
        "-C",
        vaultPath,
        "--output-last-message",
        outPath,
        "-"
      ];
      if (this.settings.codexModel.trim()) {
        args.splice(1, 0, "--model", this.settings.codexModel.trim());
      }
      const nodeBin = this.resolveNodeBinary(this.settings.nodePath);
      await this.runCommand(nodeBin, [codexBin, ...args], prompt, vaultPath);
      stdout = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : "";
      if (fs.existsSync(outPath)) fs.unlinkSync(outPath);
      if (fs.existsSync(schemaPath)) fs.unlinkSync(schemaPath);
    } else {
      const claudeBin = this.resolveLocalCliBinary("claude", this.settings.claudePath);
      const args = ["-p", "--output-format", "text"];
      if (this.settings.claudeModel.trim()) {
        args.push("--model", this.settings.claudeModel.trim());
      }
      args.push(prompt);
      stdout = await this.runCommand(claudeBin, args, void 0, vaultPath);
    }
    return this.parsePackFromText(stdout);
  }
  async generateViaOpenAI(title, noteContent) {
    const prompt = this.buildPrompt(title, noteContent);
    const res = await (0, import_obsidian.requestUrl)({
      url: "https://api.openai.com/v1/chat/completions",
      method: "POST",
      headers: {
        Authorization: `Bearer ${this.settings.openaiApiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: this.settings.openaiModel,
        messages: [{ role: "user", content: prompt }],
        temperature: 0.2,
        response_format: { type: "json_object" }
      })
    });
    const raw = res.json?.choices?.[0]?.message?.content ?? "{}";
    return this.parsePackFromText(raw);
  }
  parsePackFromText(rawText) {
    const raw = rawText?.trim() || "{}";
    let parsed = {};
    try {
      parsed = JSON.parse(raw);
    } catch {
      const first = raw.indexOf("{");
      const last = raw.lastIndexOf("}");
      if (first >= 0 && last > first) {
        try {
          parsed = JSON.parse(raw.slice(first, last + 1));
        } catch {
          parsed = {};
        }
      }
    }
    return {
      insight: parsed.insight?.trim() || "Refine this blip into a concrete next action.",
      nextSteps: parsed.nextSteps?.filter(Boolean).slice(0, 3) || [
        "Take one small concrete step and note the result."
      ],
      reminder: parsed.reminder?.trim() || "Small execution beats perfect planning."
    };
  }
  generateFallback(title, noteContent) {
    const text = `${title}
${noteContent}`.toLowerCase();
    if (text.includes("kafka") || text.includes("tcp") || text.includes("queue")) {
      return {
        insight: "This blip has strong implementation value; convert it into one tiny experiment before reading more.",
        nextSteps: [
          "Read one practical article on Kafka over TCP internals (15\u201320 min cap).",
          "Build a mini PoC: single producer + consumer with one observable metric (latency or retries).",
          "Write 5 bullet learnings in this same note and link to one related system-design note."
        ],
        reminder: "Ship one artifact, not just one reading."
      };
    }
    if (text.includes("protein") || text.includes("soya") || text.includes("diet") || text.includes("food")) {
      return {
        insight: "This is a behavior-change blip; the fastest clarity comes from a 7-day measured trial.",
        nextSteps: [
          "Pick one daily soya/protein plan and run it for 7 days.",
          "Track satiety, digestion, and energy in one line per day in this note.",
          "At day 7, keep/adjust/drop based on evidence, not mood."
        ],
        reminder: "One controlled experiment beats endless nutrition browsing."
      };
    }
    return {
      insight: "Narrow this into a concrete next action to preserve momentum.",
      nextSteps: [
        "Define the smallest testable action (<=25 min).",
        "Do it once this week and capture outcome in this note.",
        "Add one link to a related note for context continuity."
      ],
      reminder: "Prefer completion artifacts over more inputs."
    };
  }
  resolveLocalCliBinary(kind, configuredPath) {
    const req = this.nodeRequire();
    const fs = req("fs");
    const path = req("path");
    const candidates = [
      configuredPath,
      kind,
      path.join("/Users/parashuram/.npm-global/bin", kind),
      path.join("/Users/parashuram/.local/bin", kind),
      path.join(process.env.HOME || "", ".npm-global/bin", kind),
      path.join(process.env.HOME || "", ".local/bin", kind),
      `/opt/homebrew/bin/${kind}`,
      `/usr/local/bin/${kind}`,
      `/usr/bin/${kind}`
    ].filter(Boolean);
    for (const c of candidates) {
      if (!c) continue;
      if (c === kind) return c;
      if (fs.existsSync(c)) return c;
    }
    throw new Error(
      `${kind} binary not found (ENOENT). Set Blip Resurfacer ${kind === "codex" ? "Codex" : "Claude"} path in settings.`
    );
  }
  resolveNodeBinary(configuredPath) {
    const req = this.nodeRequire();
    const fs = req("fs");
    const candidates = [configuredPath, "/opt/homebrew/bin/node", "/usr/local/bin/node", "node"];
    for (const c of candidates) {
      if (!c) continue;
      if (c === "node") return c;
      if (fs.existsSync(c)) return c;
    }
    throw new Error("node binary not found. Set Node path in Blip Resurfacer settings.");
  }
  async runCommand(command, args, stdinText, cwd) {
    const req = this.nodeRequire();
    const cp = req("child_process");
    return await new Promise((resolve, reject) => {
      const child = cp.spawn(command, args, {
        cwd,
        shell: false,
        env: process.env
      });
      let stdout = "";
      let stderr = "";
      child.stdout?.on("data", (d) => stdout += d.toString("utf8"));
      child.stderr?.on("data", (d) => stderr += d.toString("utf8"));
      child.on("error", (err) => {
        if (err?.code === "ENOENT") {
          reject(new Error(`${command} not found (ENOENT). Check CLI path in plugin settings.`));
          return;
        }
        reject(err);
      });
      child.on("close", (code) => {
        if (code === 0) resolve(stdout.trim());
        else reject(new Error(`${command} exited ${code}: ${stderr || stdout}`));
      });
      if (stdinText && child.stdin) {
        child.stdin.write(stdinText);
      }
      child.stdin?.end();
    });
  }
  nodeRequire() {
    const req = window.require;
    if (!req) {
      throw new Error("Node require() unavailable. Local CLI mode needs desktop Obsidian.");
    }
    return req;
  }
  formatDate(d) {
    return d.toISOString().slice(0, 10);
  }
};
var BlipResurfacerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Blip Resurfacer" });
    new import_obsidian.Setting(containerEl).setName("Max daily resurfaced blips").setDesc("How many blips to update in one run").addText(
      (text) => text.setValue(String(this.plugin.settings.maxDailyResurface)).onChange(async (value) => {
        const n = Number(value);
        if (!Number.isNaN(n) && n > 0) {
          this.plugin.settings.maxDailyResurface = n;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("AI provider").setDesc("Use local Codex/Claude CLI by default (no API key needed).").addDropdown(
      (dd) => dd.addOption("local-cli", "Local CLI (Codex/Claude)").addOption("openai", "OpenAI API").addOption("fallback", "Fallback only (rules)").setValue(this.plugin.settings.aiProvider).onChange(async (value) => {
        this.plugin.settings.aiProvider = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.aiProvider === "local-cli") {
      new import_obsidian.Setting(containerEl).setName("Local CLI").setDesc("Select which installed CLI to use").addDropdown(
        (dd) => dd.addOption("codex", "Codex").addOption("claude", "Claude").setValue(this.plugin.settings.localCli).onChange(async (value) => {
          this.plugin.settings.localCli = value;
          await this.plugin.saveSettings();
          this.display();
        })
      );
      new import_obsidian.Setting(containerEl).setName("Strict local AI mode").setDesc("If local CLI fails, stop run instead of silently using generic fallback").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.strictLocalAi).onChange(async (value) => {
          this.plugin.settings.strictLocalAi = value;
          await this.plugin.saveSettings();
        })
      );
      if (this.plugin.settings.localCli === "codex") {
        new import_obsidian.Setting(containerEl).setName("Codex binary path").setDesc("Absolute path preferred (fixes ENOENT on some Obsidian PATH setups)").addText(
          (text) => text.setPlaceholder("/Users/you/.npm-global/bin/codex").setValue(this.plugin.settings.codexPath).onChange(async (value) => {
            this.plugin.settings.codexPath = value.trim();
            await this.plugin.saveSettings();
          })
        );
        new import_obsidian.Setting(containerEl).setName("Node binary path (for Codex)").setDesc("Used to run Codex JS entrypoint when env PATH is missing node").addText(
          (text) => text.setPlaceholder("/opt/homebrew/bin/node").setValue(this.plugin.settings.nodePath).onChange(async (value) => {
            this.plugin.settings.nodePath = value.trim();
            await this.plugin.saveSettings();
          })
        );
        new import_obsidian.Setting(containerEl).setName("Codex model (optional)").addText(
          (text) => text.setPlaceholder("e.g. gpt-5-codex").setValue(this.plugin.settings.codexModel).onChange(async (value) => {
            this.plugin.settings.codexModel = value.trim();
            await this.plugin.saveSettings();
          })
        );
      } else {
        new import_obsidian.Setting(containerEl).setName("Claude binary path").setDesc("Absolute path preferred (fixes ENOENT on some Obsidian PATH setups)").addText(
          (text) => text.setPlaceholder("/Users/you/.local/bin/claude").setValue(this.plugin.settings.claudePath).onChange(async (value) => {
            this.plugin.settings.claudePath = value.trim();
            await this.plugin.saveSettings();
          })
        );
        new import_obsidian.Setting(containerEl).setName("Claude model (optional)").addText(
          (text) => text.setPlaceholder("e.g. sonnet").setValue(this.plugin.settings.claudeModel).onChange(async (value) => {
            this.plugin.settings.claudeModel = value.trim();
            await this.plugin.saveSettings();
          })
        );
      }
    }
    if (this.plugin.settings.aiProvider === "openai") {
      new import_obsidian.Setting(containerEl).setName("OpenAI API key").addText(
        (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
          this.plugin.settings.openaiApiKey = value.trim();
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("OpenAI model").addText(
        (text) => text.setValue(this.plugin.settings.openaiModel).onChange(async (value) => {
          this.plugin.settings.openaiModel = value.trim() || "gpt-4o-mini";
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("User context").setDesc("Used to tailor next quality steps").addTextArea(
      (text) => text.setValue(this.plugin.settings.userContext).onChange(async (value) => {
        this.plugin.settings.userContext = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Run now").setDesc("Manually resurface blips and update notes in-place").addButton(
      (btn) => btn.setButtonText("Resurface now").onClick(async () => {
        const count = await this.plugin.resurfaceNow();
        new import_obsidian.Notice(`Blip Resurfacer: updated ${count} blip(s)`);
      })
    );
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsibWFpbi50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaW1wb3J0IHtcbiAgQXBwLFxuICBOb3RpY2UsXG4gIFBsdWdpbixcbiAgUGx1Z2luU2V0dGluZ1RhYixcbiAgU2V0dGluZyxcbiAgVEZpbGUsXG4gIHJlcXVlc3RVcmxcbn0gZnJvbSAnb2JzaWRpYW4nO1xuXG50eXBlIEJsaXBQYWNrID0ge1xuICBpbnNpZ2h0OiBzdHJpbmc7XG4gIG5leHRTdGVwczogc3RyaW5nW107XG4gIHJlbWluZGVyOiBzdHJpbmc7XG59O1xuXG50eXBlIEFpUHJvdmlkZXIgPSAnbG9jYWwtY2xpJyB8ICdvcGVuYWknIHwgJ2ZhbGxiYWNrJztcbnR5cGUgTG9jYWxDbGkgPSAnY29kZXgnIHwgJ2NsYXVkZSc7XG5cbmludGVyZmFjZSBCbGlwUmVzdXJmYWNlclNldHRpbmdzIHtcbiAgbWF4RGFpbHlSZXN1cmZhY2U6IG51bWJlcjtcbiAgYWlQcm92aWRlcjogQWlQcm92aWRlcjtcbiAgbG9jYWxDbGk6IExvY2FsQ2xpO1xuICBzdHJpY3RMb2NhbEFpOiBib29sZWFuO1xuICBjb2RleE1vZGVsOiBzdHJpbmc7XG4gIGNsYXVkZU1vZGVsOiBzdHJpbmc7XG4gIGNvZGV4UGF0aDogc3RyaW5nO1xuICBjbGF1ZGVQYXRoOiBzdHJpbmc7XG4gIG5vZGVQYXRoOiBzdHJpbmc7XG4gIG9wZW5haUFwaUtleTogc3RyaW5nO1xuICBvcGVuYWlNb2RlbDogc3RyaW5nO1xuICB1c2VyQ29udGV4dDogc3RyaW5nO1xufVxuXG5jb25zdCBERUZBVUxUX1NFVFRJTkdTOiBCbGlwUmVzdXJmYWNlclNldHRpbmdzID0ge1xuICBtYXhEYWlseVJlc3VyZmFjZTogMixcbiAgYWlQcm92aWRlcjogJ2xvY2FsLWNsaScsXG4gIGxvY2FsQ2xpOiAnY29kZXgnLFxuICBzdHJpY3RMb2NhbEFpOiB0cnVlLFxuICBjb2RleE1vZGVsOiAnZ3B0LTUtY29kZXgnLFxuICBjbGF1ZGVNb2RlbDogJ3Nvbm5ldCcsXG4gIGNvZGV4UGF0aDogJy9Vc2Vycy9wYXJhc2h1cmFtLy5ucG0tZ2xvYmFsL2Jpbi9jb2RleCcsXG4gIGNsYXVkZVBhdGg6ICcvVXNlcnMvcGFyYXNodXJhbS8ubG9jYWwvYmluL2NsYXVkZScsXG4gIG5vZGVQYXRoOiAnL29wdC9ob21lYnJldy9iaW4vbm9kZScsXG4gIG9wZW5haUFwaUtleTogJycsXG4gIG9wZW5haU1vZGVsOiAnZ3B0LTRvLW1pbmknLFxuICB1c2VyQ29udGV4dDpcbiAgICAnVXNlciBpcyBhbiBleHBlcmllbmNlZCBiYWNrZW5kIGVuZ2luZWVyLiBQcmVmZXIgY29uY3JldGUsIHNtYWxsIG5leHQgc3RlcHMgYW5kIHByYWN0aWNhbCBtaW5pLVBPQ3MuJ1xufTtcblxuZXhwb3J0IGRlZmF1bHQgY2xhc3MgQmxpcFJlc3VyZmFjZXJQbHVnaW4gZXh0ZW5kcyBQbHVnaW4ge1xuICBzZXR0aW5nczogQmxpcFJlc3VyZmFjZXJTZXR0aW5ncyA9IERFRkFVTFRfU0VUVElOR1M7XG5cbiAgYXN5bmMgb25sb2FkKCkge1xuICAgIGF3YWl0IHRoaXMubG9hZFNldHRpbmdzKCk7XG5cbiAgICB0aGlzLmFkZENvbW1hbmQoe1xuICAgICAgaWQ6ICdyZXN1cmZhY2UtYmxpcHMtbm93JyxcbiAgICAgIG5hbWU6ICdSZXN1cmZhY2UgYmxpcHMgbm93JyxcbiAgICAgIGNhbGxiYWNrOiBhc3luYyAoKSA9PiB7XG4gICAgICAgIGNvbnN0IGNvdW50ID0gYXdhaXQgdGhpcy5yZXN1cmZhY2VOb3coKTtcbiAgICAgICAgbmV3IE5vdGljZShgQmxpcCBSZXN1cmZhY2VyOiB1cGRhdGVkICR7Y291bnR9IGJsaXAocylgKTtcbiAgICAgIH1cbiAgICB9KTtcblxuICAgIHRoaXMuYWRkQ29tbWFuZCh7XG4gICAgICBpZDogJ3Rlc3QtbG9jYWwtYWktYmFja2VuZCcsXG4gICAgICBuYW1lOiAnVGVzdCBsb2NhbCBBSSBiYWNrZW5kIChDb2RleC9DbGF1ZGUpJyxcbiAgICAgIGNhbGxiYWNrOiBhc3luYyAoKSA9PiB7XG4gICAgICAgIHRyeSB7XG4gICAgICAgICAgY29uc3QgcGFjayA9IGF3YWl0IHRoaXMuZ2VuZXJhdGVWaWFMb2NhbENsaShcbiAgICAgICAgICAgICdCYWNrZW5kIGNvbm5lY3Rpdml0eSB0ZXN0JyxcbiAgICAgICAgICAgICdDcmVhdGUgb25lIGluc2lnaHQgYW5kIHR3byBwcmFjdGljYWwgc3RlcHMgYWJvdXQgbGVhcm5pbmcgS2Fma2Egb3ZlciBUQ1AuJ1xuICAgICAgICAgICk7XG4gICAgICAgICAgbmV3IE5vdGljZShgTG9jYWwgQUkgT0sgKCR7dGhpcy5zZXR0aW5ncy5sb2NhbENsaX0pLiBJbnNpZ2h0OiAke3BhY2suaW5zaWdodC5zbGljZSgwLCA4MCl9Li4uYCk7XG4gICAgICAgIH0gY2F0Y2ggKGUpIHtcbiAgICAgICAgICBuZXcgTm90aWNlKGBMb2NhbCBBSSBmYWlsZWQgKCR7dGhpcy5zZXR0aW5ncy5sb2NhbENsaX0pOiAke1N0cmluZygoZSBhcyBFcnJvcik/Lm1lc3NhZ2UgfHwgZSkuc2xpY2UoMCwgMTQwKX1gKTtcbiAgICAgICAgfVxuICAgICAgfVxuICAgIH0pO1xuXG4gICAgdGhpcy5hZGRTZXR0aW5nVGFiKG5ldyBCbGlwUmVzdXJmYWNlclNldHRpbmdUYWIodGhpcy5hcHAsIHRoaXMpKTtcbiAgfVxuXG4gIGFzeW5jIGxvYWRTZXR0aW5ncygpIHtcbiAgICBjb25zdCBsb2FkZWQgPSBPYmplY3QuYXNzaWduKHt9LCBERUZBVUxUX1NFVFRJTkdTLCBhd2FpdCB0aGlzLmxvYWREYXRhKCkpIGFzIEJsaXBSZXN1cmZhY2VyU2V0dGluZ3MgJiB7XG4gICAgICBhaUVuYWJsZWQ/OiBib29sZWFuO1xuICAgIH07XG5cbiAgICAvLyBMZWdhY3kgbWlncmF0aW9uIGZyb20gdjAuMS4wIGtleXNcbiAgICBpZiAodHlwZW9mIGxvYWRlZC5haUVuYWJsZWQgPT09ICdib29sZWFuJykge1xuICAgICAgaWYgKCFsb2FkZWQuYWlFbmFibGVkKSBsb2FkZWQuYWlQcm92aWRlciA9ICdmYWxsYmFjayc7XG4gICAgICBlbHNlIGlmIChsb2FkZWQuYWlQcm92aWRlciA9PT0gJ2ZhbGxiYWNrJykgbG9hZGVkLmFpUHJvdmlkZXIgPSAnbG9jYWwtY2xpJztcbiAgICB9XG5cbiAgICAvLyBOb3JtYWxpemUga25vd24tYmFkIGxvY2FsIG1vZGVsIG5hbWVzXG4gICAgaWYgKCFsb2FkZWQuY29kZXhNb2RlbD8udHJpbSgpIHx8IGxvYWRlZC5jb2RleE1vZGVsLmluY2x1ZGVzKCdncHQtNS4zLWNvZGV4JykpIHtcbiAgICAgIGxvYWRlZC5jb2RleE1vZGVsID0gJ2dwdC01LWNvZGV4JztcbiAgICB9XG4gICAgaWYgKCFsb2FkZWQuY2xhdWRlTW9kZWw/LnRyaW0oKSkge1xuICAgICAgbG9hZGVkLmNsYXVkZU1vZGVsID0gJ3Nvbm5ldCc7XG4gICAgfVxuICAgIGlmICghbG9hZGVkLmNvZGV4UGF0aD8udHJpbSgpKSB7XG4gICAgICBsb2FkZWQuY29kZXhQYXRoID0gJy9Vc2Vycy9wYXJhc2h1cmFtLy5ucG0tZ2xvYmFsL2Jpbi9jb2RleCc7XG4gICAgfVxuICAgIGlmICghbG9hZGVkLmNsYXVkZVBhdGg/LnRyaW0oKSkge1xuICAgICAgbG9hZGVkLmNsYXVkZVBhdGggPSAnL1VzZXJzL3BhcmFzaHVyYW0vLmxvY2FsL2Jpbi9jbGF1ZGUnO1xuICAgIH1cbiAgICBpZiAoIWxvYWRlZC5ub2RlUGF0aD8udHJpbSgpKSB7XG4gICAgICBsb2FkZWQubm9kZVBhdGggPSAnL29wdC9ob21lYnJldy9iaW4vbm9kZSc7XG4gICAgfVxuXG4gICAgdGhpcy5zZXR0aW5ncyA9IGxvYWRlZDtcbiAgfVxuXG4gIGFzeW5jIHNhdmVTZXR0aW5ncygpIHtcbiAgICBhd2FpdCB0aGlzLnNhdmVEYXRhKHRoaXMuc2V0dGluZ3MpO1xuICB9XG5cbiAgYXN5bmMgcmVzdXJmYWNlTm93KCk6IFByb21pc2U8bnVtYmVyPiB7XG4gICAgY29uc3QgYmxpcHMgPSBhd2FpdCB0aGlzLmdldEJsaXBGaWxlcygpO1xuICAgIGlmICghYmxpcHMubGVuZ3RoKSB7XG4gICAgICBuZXcgTm90aWNlKCdObyBub3RlcyB3aXRoIHR5cGU6IGJsaXAgZm91bmQuJyk7XG4gICAgICByZXR1cm4gMDtcbiAgICB9XG5cbiAgICBjb25zdCBzZWxlY3RlZCA9IGJsaXBzLnNsaWNlKDAsIE1hdGgubWF4KDEsIHRoaXMuc2V0dGluZ3MubWF4RGFpbHlSZXN1cmZhY2UpKTtcblxuICAgIGZvciAoY29uc3QgZmlsZSBvZiBzZWxlY3RlZCkge1xuICAgICAgY29uc3QgdGV4dCA9IGF3YWl0IHRoaXMuYXBwLnZhdWx0LnJlYWQoZmlsZSk7XG4gICAgICBjb25zdCBwYWNrID0gYXdhaXQgdGhpcy5nZW5lcmF0ZUJsaXBQYWNrKGZpbGUuYmFzZW5hbWUsIHRleHQpO1xuICAgICAgYXdhaXQgdGhpcy5hcHBlbmRCbGlwVXBkYXRlKGZpbGUsIHBhY2spO1xuICAgIH1cblxuICAgIHJldHVybiBzZWxlY3RlZC5sZW5ndGg7XG4gIH1cblxuICBwcml2YXRlIGFzeW5jIGdldEJsaXBGaWxlcygpOiBQcm9taXNlPFRGaWxlW10+IHtcbiAgICByZXR1cm4gdGhpcy5hcHAudmF1bHQuZ2V0TWFya2Rvd25GaWxlcygpXG4gICAgICAuZmlsdGVyKChmaWxlKSA9PiB7XG4gICAgICAgIGNvbnN0IGNhY2hlID0gdGhpcy5hcHAubWV0YWRhdGFDYWNoZS5nZXRGaWxlQ2FjaGUoZmlsZSk7XG4gICAgICAgIGNvbnN0IGZtID0gY2FjaGU/LmZyb250bWF0dGVyIGFzIFJlY29yZDxzdHJpbmcsIHVua25vd24+IHwgdW5kZWZpbmVkO1xuICAgICAgICByZXR1cm4gZm0gJiYgU3RyaW5nKGZtLnR5cGUgPz8gJycpLnRvTG93ZXJDYXNlKCkgPT09ICdibGlwJztcbiAgICAgIH0pXG4gICAgICAuc29ydCgoYSwgYikgPT4gYS5zdGF0Lm10aW1lIC0gYi5zdGF0Lm10aW1lKTtcbiAgfVxuXG4gIHByaXZhdGUgYXN5bmMgYXBwZW5kQmxpcFVwZGF0ZShmaWxlOiBURmlsZSwgcGFjazogQmxpcFBhY2spIHtcbiAgICBjb25zdCBkYXRlU3RyID0gdGhpcy5mb3JtYXREYXRlKG5ldyBEYXRlKCkpO1xuICAgIGNvbnN0IHNlY3Rpb25IZWFkZXIgPSAnIyMgQmxpcCB1cGRhdGVzIChDbGF3ZCknO1xuXG4gICAgY29uc3QgZW50cnkgPSBbXG4gICAgICBgIyMjICR7ZGF0ZVN0cn1gLFxuICAgICAgYC0gR2VuZXJhdGVkIGJ5OiAke3RoaXMuc2V0dGluZ3MuYWlQcm92aWRlciA9PT0gJ2xvY2FsLWNsaScgPyB0aGlzLnNldHRpbmdzLmxvY2FsQ2xpIDogdGhpcy5zZXR0aW5ncy5haVByb3ZpZGVyfWAsXG4gICAgICBgLSBJbnNpZ2h0OiAke3BhY2suaW5zaWdodH1gLFxuICAgICAgYC0gTmV4dCBxdWFsaXR5IHN0ZXBzOmAsXG4gICAgICAuLi5wYWNrLm5leHRTdGVwcy5tYXAoKHMpID0+IGAgIC0gJHtzfWApLFxuICAgICAgYC0gUmVtaW5kZXI6ICR7cGFjay5yZW1pbmRlcn1gLFxuICAgICAgJydcbiAgICBdLmpvaW4oJ1xcbicpO1xuXG4gICAgY29uc3QgY29udGVudCA9IGF3YWl0IHRoaXMuYXBwLnZhdWx0LnJlYWQoZmlsZSk7XG5cbiAgICBpZiAoY29udGVudC5pbmNsdWRlcyhzZWN0aW9uSGVhZGVyKSkge1xuICAgICAgYXdhaXQgdGhpcy5hcHAudmF1bHQubW9kaWZ5KGZpbGUsIGAke2NvbnRlbnQudHJpbUVuZCgpfVxcblxcbiR7ZW50cnl9YCk7XG4gICAgICByZXR1cm47XG4gICAgfVxuXG4gICAgY29uc3QgdXBkYXRlZCA9IGAke2NvbnRlbnQudHJpbUVuZCgpfVxcblxcbiR7c2VjdGlvbkhlYWRlcn1cXG5cXG4ke2VudHJ5fWA7XG4gICAgYXdhaXQgdGhpcy5hcHAudmF1bHQubW9kaWZ5KGZpbGUsIHVwZGF0ZWQpO1xuICB9XG5cbiAgcHJpdmF0ZSBhc3luYyBnZW5lcmF0ZUJsaXBQYWNrKHRpdGxlOiBzdHJpbmcsIG5vdGVDb250ZW50OiBzdHJpbmcpOiBQcm9taXNlPEJsaXBQYWNrPiB7XG4gICAgaWYgKHRoaXMuc2V0dGluZ3MuYWlQcm92aWRlciA9PT0gJ2xvY2FsLWNsaScpIHtcbiAgICAgIHRyeSB7XG4gICAgICAgIHJldHVybiBhd2FpdCB0aGlzLmdlbmVyYXRlVmlhTG9jYWxDbGkodGl0bGUsIG5vdGVDb250ZW50KTtcbiAgICAgIH0gY2F0Y2ggKGUpIHtcbiAgICAgICAgY29uc3QgbXNnID0gU3RyaW5nKChlIGFzIEVycm9yKT8ubWVzc2FnZSB8fCBlKTtcbiAgICAgICAgY29uc29sZS5lcnJvcignQmxpcCBSZXN1cmZhY2VyIGxvY2FsIENMSSBmYWlsZWQnLCBlKTtcbiAgICAgICAgbmV3IE5vdGljZShgQmxpcCBSZXN1cmZhY2VyOiBsb2NhbCAke3RoaXMuc2V0dGluZ3MubG9jYWxDbGl9IGZhaWxlZCAoJHttc2cuc2xpY2UoMCwgMTIwKX0pYCk7XG4gICAgICAgIGlmICh0aGlzLnNldHRpbmdzLnN0cmljdExvY2FsQWkpIHtcbiAgICAgICAgICB0aHJvdyBlO1xuICAgICAgICB9XG4gICAgICB9XG4gICAgfVxuXG4gICAgaWYgKHRoaXMuc2V0dGluZ3MuYWlQcm92aWRlciA9PT0gJ29wZW5haScgJiYgdGhpcy5zZXR0aW5ncy5vcGVuYWlBcGlLZXkudHJpbSgpKSB7XG4gICAgICB0cnkge1xuICAgICAgICByZXR1cm4gYXdhaXQgdGhpcy5nZW5lcmF0ZVZpYU9wZW5BSSh0aXRsZSwgbm90ZUNvbnRlbnQpO1xuICAgICAgfSBjYXRjaCAoZSkge1xuICAgICAgICBjb25zb2xlLmVycm9yKCdCbGlwIFJlc3VyZmFjZXIgT3BlbkFJIGZhaWxlZCwgdXNpbmcgZmFsbGJhY2snLCBlKTtcbiAgICAgIH1cbiAgICB9XG5cbiAgICByZXR1cm4gdGhpcy5nZW5lcmF0ZUZhbGxiYWNrKHRpdGxlLCBub3RlQ29udGVudCk7XG4gIH1cblxuICBwcml2YXRlIGJ1aWxkUHJvbXB0KHRpdGxlOiBzdHJpbmcsIG5vdGVDb250ZW50OiBzdHJpbmcpOiBzdHJpbmcge1xuICAgIHJldHVybiBgWW91IGhlbHAgcmVzdXJmYWNlIHBlcnNvbmFsIE9ic2lkaWFuIGJsaXBzIGluLXBsYWNlLlxuXG5Db250ZXh0OlxuLSAke3RoaXMuc2V0dGluZ3MudXNlckNvbnRleHR9XG4tIEtlZXAgb3V0cHV0IHByYWN0aWNhbCwgc21hbGwsIGFuZCBleGVjdXRpb24tZmlyc3QuXG4tIE91dHB1dCBtdXN0IGJlIHZhbGlkIEpTT04gb25seS5cblxuQmxpcCB0aXRsZTogJHt0aXRsZX1cbkJsaXAgY29udGVudCBleGNlcnB0OlxuJHtub3RlQ29udGVudC5zbGljZSgwLCAzNTAwKX1cblxuUmV0dXJuIEpTT04gZXhhY3RseSB3aXRoIGtleXM6XG57XG4gIFwiaW5zaWdodFwiOiBcInN0cmluZyAobWF4IDIgbGluZXMpXCIsXG4gIFwibmV4dFN0ZXBzXCI6IFtcIjItMyBjb25jcmV0ZSBzdGVwc1wiXSxcbiAgXCJyZW1pbmRlclwiOiBcIm9uZSBzaG9ydCByZW1pbmRlclwiXG59YDtcbiAgfVxuXG4gIHByaXZhdGUgYXN5bmMgZ2VuZXJhdGVWaWFMb2NhbENsaSh0aXRsZTogc3RyaW5nLCBub3RlQ29udGVudDogc3RyaW5nKTogUHJvbWlzZTxCbGlwUGFjaz4ge1xuICAgIGNvbnN0IHByb21wdCA9IHRoaXMuYnVpbGRQcm9tcHQodGl0bGUsIG5vdGVDb250ZW50KTtcbiAgICBjb25zdCB2YXVsdFBhdGggPSB0aGlzLmFwcC52YXVsdC5hZGFwdGVyLmdldEJhc2VQYXRoKCk7XG5cbiAgICBsZXQgc3Rkb3V0ID0gJyc7XG5cbiAgICBpZiAodGhpcy5zZXR0aW5ncy5sb2NhbENsaSA9PT0gJ2NvZGV4Jykge1xuICAgICAgY29uc3QgcmVxID0gdGhpcy5ub2RlUmVxdWlyZSgpO1xuICAgICAgY29uc3QgZnMgPSByZXEoJ2ZzJykgYXMgdHlwZW9mIGltcG9ydCgnZnMnKTtcbiAgICAgIGNvbnN0IG9zID0gcmVxKCdvcycpIGFzIHR5cGVvZiBpbXBvcnQoJ29zJyk7XG4gICAgICBjb25zdCBwYXRoID0gcmVxKCdwYXRoJykgYXMgdHlwZW9mIGltcG9ydCgncGF0aCcpO1xuICAgICAgY29uc3QgY29kZXhCaW4gPSB0aGlzLnJlc29sdmVMb2NhbENsaUJpbmFyeSgnY29kZXgnLCB0aGlzLnNldHRpbmdzLmNvZGV4UGF0aCk7XG4gICAgICBjb25zdCBvdXRQYXRoID0gcGF0aC5qb2luKG9zLnRtcGRpcigpLCBgYmxpcC1yZXN1cmZhY2VyLSR7RGF0ZS5ub3coKX0uanNvbmApO1xuICAgICAgY29uc3Qgc2NoZW1hUGF0aCA9IHBhdGguam9pbihvcy50bXBkaXIoKSwgYGJsaXAtcmVzdXJmYWNlci1zY2hlbWEtJHtEYXRlLm5vdygpfS5qc29uYCk7XG4gICAgICBmcy53cml0ZUZpbGVTeW5jKFxuICAgICAgICBzY2hlbWFQYXRoLFxuICAgICAgICBKU09OLnN0cmluZ2lmeSh7XG4gICAgICAgICAgdHlwZTogJ29iamVjdCcsXG4gICAgICAgICAgYWRkaXRpb25hbFByb3BlcnRpZXM6IGZhbHNlLFxuICAgICAgICAgIHJlcXVpcmVkOiBbJ2luc2lnaHQnLCAnbmV4dFN0ZXBzJywgJ3JlbWluZGVyJ10sXG4gICAgICAgICAgcHJvcGVydGllczoge1xuICAgICAgICAgICAgaW5zaWdodDogeyB0eXBlOiAnc3RyaW5nJyB9LFxuICAgICAgICAgICAgbmV4dFN0ZXBzOiB7IHR5cGU6ICdhcnJheScsIG1pbkl0ZW1zOiAyLCBtYXhJdGVtczogMywgaXRlbXM6IHsgdHlwZTogJ3N0cmluZycgfSB9LFxuICAgICAgICAgICAgcmVtaW5kZXI6IHsgdHlwZTogJ3N0cmluZycgfVxuICAgICAgICAgIH1cbiAgICAgICAgfSlcbiAgICAgICk7XG5cbiAgICAgIGNvbnN0IGFyZ3MgPSBbXG4gICAgICAgICdleGVjJyxcbiAgICAgICAgJy0tc2tpcC1naXQtcmVwby1jaGVjaycsXG4gICAgICAgICctLW91dHB1dC1zY2hlbWEnLFxuICAgICAgICBzY2hlbWFQYXRoLFxuICAgICAgICAnLUMnLFxuICAgICAgICB2YXVsdFBhdGgsXG4gICAgICAgICctLW91dHB1dC1sYXN0LW1lc3NhZ2UnLFxuICAgICAgICBvdXRQYXRoLFxuICAgICAgICAnLSdcbiAgICAgIF07XG4gICAgICBpZiAodGhpcy5zZXR0aW5ncy5jb2RleE1vZGVsLnRyaW0oKSkge1xuICAgICAgICBhcmdzLnNwbGljZSgxLCAwLCAnLS1tb2RlbCcsIHRoaXMuc2V0dGluZ3MuY29kZXhNb2RlbC50cmltKCkpO1xuICAgICAgfVxuXG4gICAgICBjb25zdCBub2RlQmluID0gdGhpcy5yZXNvbHZlTm9kZUJpbmFyeSh0aGlzLnNldHRpbmdzLm5vZGVQYXRoKTtcbiAgICAgIGF3YWl0IHRoaXMucnVuQ29tbWFuZChub2RlQmluLCBbY29kZXhCaW4sIC4uLmFyZ3NdLCBwcm9tcHQsIHZhdWx0UGF0aCk7XG4gICAgICBzdGRvdXQgPSBmcy5leGlzdHNTeW5jKG91dFBhdGgpID8gZnMucmVhZEZpbGVTeW5jKG91dFBhdGgsICd1dGY4JykgOiAnJztcbiAgICAgIGlmIChmcy5leGlzdHNTeW5jKG91dFBhdGgpKSBmcy51bmxpbmtTeW5jKG91dFBhdGgpO1xuICAgICAgaWYgKGZzLmV4aXN0c1N5bmMoc2NoZW1hUGF0aCkpIGZzLnVubGlua1N5bmMoc2NoZW1hUGF0aCk7XG4gICAgfSBlbHNlIHtcbiAgICAgIGNvbnN0IGNsYXVkZUJpbiA9IHRoaXMucmVzb2x2ZUxvY2FsQ2xpQmluYXJ5KCdjbGF1ZGUnLCB0aGlzLnNldHRpbmdzLmNsYXVkZVBhdGgpO1xuICAgICAgY29uc3QgYXJncyA9IFsnLXAnLCAnLS1vdXRwdXQtZm9ybWF0JywgJ3RleHQnXTtcbiAgICAgIGlmICh0aGlzLnNldHRpbmdzLmNsYXVkZU1vZGVsLnRyaW0oKSkge1xuICAgICAgICBhcmdzLnB1c2goJy0tbW9kZWwnLCB0aGlzLnNldHRpbmdzLmNsYXVkZU1vZGVsLnRyaW0oKSk7XG4gICAgICB9XG4gICAgICBhcmdzLnB1c2gocHJvbXB0KTtcbiAgICAgIHN0ZG91dCA9IGF3YWl0IHRoaXMucnVuQ29tbWFuZChjbGF1ZGVCaW4sIGFyZ3MsIHVuZGVmaW5lZCwgdmF1bHRQYXRoKTtcbiAgICB9XG5cbiAgICByZXR1cm4gdGhpcy5wYXJzZVBhY2tGcm9tVGV4dChzdGRvdXQpO1xuICB9XG5cbiAgcHJpdmF0ZSBhc3luYyBnZW5lcmF0ZVZpYU9wZW5BSSh0aXRsZTogc3RyaW5nLCBub3RlQ29udGVudDogc3RyaW5nKTogUHJvbWlzZTxCbGlwUGFjaz4ge1xuICAgIGNvbnN0IHByb21wdCA9IHRoaXMuYnVpbGRQcm9tcHQodGl0bGUsIG5vdGVDb250ZW50KTtcblxuICAgIGNvbnN0IHJlcyA9IGF3YWl0IHJlcXVlc3RVcmwoe1xuICAgICAgdXJsOiAnaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MS9jaGF0L2NvbXBsZXRpb25zJyxcbiAgICAgIG1ldGhvZDogJ1BPU1QnLFxuICAgICAgaGVhZGVyczoge1xuICAgICAgICBBdXRob3JpemF0aW9uOiBgQmVhcmVyICR7dGhpcy5zZXR0aW5ncy5vcGVuYWlBcGlLZXl9YCxcbiAgICAgICAgJ0NvbnRlbnQtVHlwZSc6ICdhcHBsaWNhdGlvbi9qc29uJ1xuICAgICAgfSxcbiAgICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5KHtcbiAgICAgICAgbW9kZWw6IHRoaXMuc2V0dGluZ3Mub3BlbmFpTW9kZWwsXG4gICAgICAgIG1lc3NhZ2VzOiBbeyByb2xlOiAndXNlcicsIGNvbnRlbnQ6IHByb21wdCB9XSxcbiAgICAgICAgdGVtcGVyYXR1cmU6IDAuMixcbiAgICAgICAgcmVzcG9uc2VfZm9ybWF0OiB7IHR5cGU6ICdqc29uX29iamVjdCcgfVxuICAgICAgfSlcbiAgICB9KTtcblxuICAgIGNvbnN0IHJhdyA9IHJlcy5qc29uPy5jaG9pY2VzPy5bMF0/Lm1lc3NhZ2U/LmNvbnRlbnQgPz8gJ3t9JztcbiAgICByZXR1cm4gdGhpcy5wYXJzZVBhY2tGcm9tVGV4dChyYXcpO1xuICB9XG5cbiAgcHJpdmF0ZSBwYXJzZVBhY2tGcm9tVGV4dChyYXdUZXh0OiBzdHJpbmcpOiBCbGlwUGFjayB7XG4gICAgY29uc3QgcmF3ID0gcmF3VGV4dD8udHJpbSgpIHx8ICd7fSc7XG4gICAgbGV0IHBhcnNlZDogUGFydGlhbDxCbGlwUGFjaz4gPSB7fTtcblxuICAgIHRyeSB7XG4gICAgICBwYXJzZWQgPSBKU09OLnBhcnNlKHJhdykgYXMgUGFydGlhbDxCbGlwUGFjaz47XG4gICAgfSBjYXRjaCB7XG4gICAgICBjb25zdCBmaXJzdCA9IHJhdy5pbmRleE9mKCd7Jyk7XG4gICAgICBjb25zdCBsYXN0ID0gcmF3Lmxhc3RJbmRleE9mKCd9Jyk7XG4gICAgICBpZiAoZmlyc3QgPj0gMCAmJiBsYXN0ID4gZmlyc3QpIHtcbiAgICAgICAgdHJ5IHtcbiAgICAgICAgICBwYXJzZWQgPSBKU09OLnBhcnNlKHJhdy5zbGljZShmaXJzdCwgbGFzdCArIDEpKSBhcyBQYXJ0aWFsPEJsaXBQYWNrPjtcbiAgICAgICAgfSBjYXRjaCB7XG4gICAgICAgICAgcGFyc2VkID0ge307XG4gICAgICAgIH1cbiAgICAgIH1cbiAgICB9XG5cbiAgICByZXR1cm4ge1xuICAgICAgaW5zaWdodDogcGFyc2VkLmluc2lnaHQ/LnRyaW0oKSB8fCAnUmVmaW5lIHRoaXMgYmxpcCBpbnRvIGEgY29uY3JldGUgbmV4dCBhY3Rpb24uJyxcbiAgICAgIG5leHRTdGVwczpcbiAgICAgICAgcGFyc2VkLm5leHRTdGVwcz8uZmlsdGVyKEJvb2xlYW4pLnNsaWNlKDAsIDMpIHx8IFtcbiAgICAgICAgICAnVGFrZSBvbmUgc21hbGwgY29uY3JldGUgc3RlcCBhbmQgbm90ZSB0aGUgcmVzdWx0LidcbiAgICAgICAgXSxcbiAgICAgIHJlbWluZGVyOiBwYXJzZWQucmVtaW5kZXI/LnRyaW0oKSB8fCAnU21hbGwgZXhlY3V0aW9uIGJlYXRzIHBlcmZlY3QgcGxhbm5pbmcuJ1xuICAgIH07XG4gIH1cblxuICBwcml2YXRlIGdlbmVyYXRlRmFsbGJhY2sodGl0bGU6IHN0cmluZywgbm90ZUNvbnRlbnQ6IHN0cmluZyk6IEJsaXBQYWNrIHtcbiAgICBjb25zdCB0ZXh0ID0gYCR7dGl0bGV9XFxuJHtub3RlQ29udGVudH1gLnRvTG93ZXJDYXNlKCk7XG5cbiAgICBpZiAodGV4dC5pbmNsdWRlcygna2Fma2EnKSB8fCB0ZXh0LmluY2x1ZGVzKCd0Y3AnKSB8fCB0ZXh0LmluY2x1ZGVzKCdxdWV1ZScpKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICBpbnNpZ2h0OlxuICAgICAgICAgICdUaGlzIGJsaXAgaGFzIHN0cm9uZyBpbXBsZW1lbnRhdGlvbiB2YWx1ZTsgY29udmVydCBpdCBpbnRvIG9uZSB0aW55IGV4cGVyaW1lbnQgYmVmb3JlIHJlYWRpbmcgbW9yZS4nLFxuICAgICAgICBuZXh0U3RlcHM6IFtcbiAgICAgICAgICAnUmVhZCBvbmUgcHJhY3RpY2FsIGFydGljbGUgb24gS2Fma2Egb3ZlciBUQ1AgaW50ZXJuYWxzICgxNVx1MjAxMzIwIG1pbiBjYXApLicsXG4gICAgICAgICAgJ0J1aWxkIGEgbWluaSBQb0M6IHNpbmdsZSBwcm9kdWNlciArIGNvbnN1bWVyIHdpdGggb25lIG9ic2VydmFibGUgbWV0cmljIChsYXRlbmN5IG9yIHJldHJpZXMpLicsXG4gICAgICAgICAgJ1dyaXRlIDUgYnVsbGV0IGxlYXJuaW5ncyBpbiB0aGlzIHNhbWUgbm90ZSBhbmQgbGluayB0byBvbmUgcmVsYXRlZCBzeXN0ZW0tZGVzaWduIG5vdGUuJ1xuICAgICAgICBdLFxuICAgICAgICByZW1pbmRlcjogJ1NoaXAgb25lIGFydGlmYWN0LCBub3QganVzdCBvbmUgcmVhZGluZy4nXG4gICAgICB9O1xuICAgIH1cblxuICAgIGlmICh0ZXh0LmluY2x1ZGVzKCdwcm90ZWluJykgfHwgdGV4dC5pbmNsdWRlcygnc295YScpIHx8IHRleHQuaW5jbHVkZXMoJ2RpZXQnKSB8fCB0ZXh0LmluY2x1ZGVzKCdmb29kJykpIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIGluc2lnaHQ6XG4gICAgICAgICAgJ1RoaXMgaXMgYSBiZWhhdmlvci1jaGFuZ2UgYmxpcDsgdGhlIGZhc3Rlc3QgY2xhcml0eSBjb21lcyBmcm9tIGEgNy1kYXkgbWVhc3VyZWQgdHJpYWwuJyxcbiAgICAgICAgbmV4dFN0ZXBzOiBbXG4gICAgICAgICAgJ1BpY2sgb25lIGRhaWx5IHNveWEvcHJvdGVpbiBwbGFuIGFuZCBydW4gaXQgZm9yIDcgZGF5cy4nLFxuICAgICAgICAgICdUcmFjayBzYXRpZXR5LCBkaWdlc3Rpb24sIGFuZCBlbmVyZ3kgaW4gb25lIGxpbmUgcGVyIGRheSBpbiB0aGlzIG5vdGUuJyxcbiAgICAgICAgICAnQXQgZGF5IDcsIGtlZXAvYWRqdXN0L2Ryb3AgYmFzZWQgb24gZXZpZGVuY2UsIG5vdCBtb29kLidcbiAgICAgICAgXSxcbiAgICAgICAgcmVtaW5kZXI6ICdPbmUgY29udHJvbGxlZCBleHBlcmltZW50IGJlYXRzIGVuZGxlc3MgbnV0cml0aW9uIGJyb3dzaW5nLidcbiAgICAgIH07XG4gICAgfVxuXG4gICAgcmV0dXJuIHtcbiAgICAgIGluc2lnaHQ6ICdOYXJyb3cgdGhpcyBpbnRvIGEgY29uY3JldGUgbmV4dCBhY3Rpb24gdG8gcHJlc2VydmUgbW9tZW50dW0uJyxcbiAgICAgIG5leHRTdGVwczogW1xuICAgICAgICAnRGVmaW5lIHRoZSBzbWFsbGVzdCB0ZXN0YWJsZSBhY3Rpb24gKDw9MjUgbWluKS4nLFxuICAgICAgICAnRG8gaXQgb25jZSB0aGlzIHdlZWsgYW5kIGNhcHR1cmUgb3V0Y29tZSBpbiB0aGlzIG5vdGUuJyxcbiAgICAgICAgJ0FkZCBvbmUgbGluayB0byBhIHJlbGF0ZWQgbm90ZSBmb3IgY29udGV4dCBjb250aW51aXR5LidcbiAgICAgIF0sXG4gICAgICByZW1pbmRlcjogJ1ByZWZlciBjb21wbGV0aW9uIGFydGlmYWN0cyBvdmVyIG1vcmUgaW5wdXRzLidcbiAgICB9O1xuICB9XG5cbiAgcHJpdmF0ZSByZXNvbHZlTG9jYWxDbGlCaW5hcnkoa2luZDogTG9jYWxDbGksIGNvbmZpZ3VyZWRQYXRoOiBzdHJpbmcpOiBzdHJpbmcge1xuICAgIGNvbnN0IHJlcSA9IHRoaXMubm9kZVJlcXVpcmUoKTtcbiAgICBjb25zdCBmcyA9IHJlcSgnZnMnKSBhcyB0eXBlb2YgaW1wb3J0KCdmcycpO1xuICAgIGNvbnN0IHBhdGggPSByZXEoJ3BhdGgnKSBhcyB0eXBlb2YgaW1wb3J0KCdwYXRoJyk7XG5cbiAgICBjb25zdCBjYW5kaWRhdGVzID0gW1xuICAgICAgY29uZmlndXJlZFBhdGgsXG4gICAgICBraW5kLFxuICAgICAgcGF0aC5qb2luKCcvVXNlcnMvcGFyYXNodXJhbS8ubnBtLWdsb2JhbC9iaW4nLCBraW5kKSxcbiAgICAgIHBhdGguam9pbignL1VzZXJzL3BhcmFzaHVyYW0vLmxvY2FsL2JpbicsIGtpbmQpLFxuICAgICAgcGF0aC5qb2luKHByb2Nlc3MuZW52LkhPTUUgfHwgJycsICcubnBtLWdsb2JhbC9iaW4nLCBraW5kKSxcbiAgICAgIHBhdGguam9pbihwcm9jZXNzLmVudi5IT01FIHx8ICcnLCAnLmxvY2FsL2JpbicsIGtpbmQpLFxuICAgICAgYC9vcHQvaG9tZWJyZXcvYmluLyR7a2luZH1gLFxuICAgICAgYC91c3IvbG9jYWwvYmluLyR7a2luZH1gLFxuICAgICAgYC91c3IvYmluLyR7a2luZH1gXG4gICAgXS5maWx0ZXIoQm9vbGVhbik7XG5cbiAgICBmb3IgKGNvbnN0IGMgb2YgY2FuZGlkYXRlcykge1xuICAgICAgaWYgKCFjKSBjb250aW51ZTtcbiAgICAgIGlmIChjID09PSBraW5kKSByZXR1cm4gYztcbiAgICAgIGlmIChmcy5leGlzdHNTeW5jKGMpKSByZXR1cm4gYztcbiAgICB9XG5cbiAgICB0aHJvdyBuZXcgRXJyb3IoXG4gICAgICBgJHtraW5kfSBiaW5hcnkgbm90IGZvdW5kIChFTk9FTlQpLiBTZXQgQmxpcCBSZXN1cmZhY2VyICR7a2luZCA9PT0gJ2NvZGV4JyA/ICdDb2RleCcgOiAnQ2xhdWRlJ30gcGF0aCBpbiBzZXR0aW5ncy5gXG4gICAgKTtcbiAgfVxuXG4gIHByaXZhdGUgcmVzb2x2ZU5vZGVCaW5hcnkoY29uZmlndXJlZFBhdGg6IHN0cmluZyk6IHN0cmluZyB7XG4gICAgY29uc3QgcmVxID0gdGhpcy5ub2RlUmVxdWlyZSgpO1xuICAgIGNvbnN0IGZzID0gcmVxKCdmcycpIGFzIHR5cGVvZiBpbXBvcnQoJ2ZzJyk7XG4gICAgY29uc3QgY2FuZGlkYXRlcyA9IFtjb25maWd1cmVkUGF0aCwgJy9vcHQvaG9tZWJyZXcvYmluL25vZGUnLCAnL3Vzci9sb2NhbC9iaW4vbm9kZScsICdub2RlJ107XG5cbiAgICBmb3IgKGNvbnN0IGMgb2YgY2FuZGlkYXRlcykge1xuICAgICAgaWYgKCFjKSBjb250aW51ZTtcbiAgICAgIGlmIChjID09PSAnbm9kZScpIHJldHVybiBjO1xuICAgICAgaWYgKGZzLmV4aXN0c1N5bmMoYykpIHJldHVybiBjO1xuICAgIH1cblxuICAgIHRocm93IG5ldyBFcnJvcignbm9kZSBiaW5hcnkgbm90IGZvdW5kLiBTZXQgTm9kZSBwYXRoIGluIEJsaXAgUmVzdXJmYWNlciBzZXR0aW5ncy4nKTtcbiAgfVxuXG4gIHByaXZhdGUgYXN5bmMgcnVuQ29tbWFuZChcbiAgICBjb21tYW5kOiBzdHJpbmcsXG4gICAgYXJnczogc3RyaW5nW10sXG4gICAgc3RkaW5UZXh0Pzogc3RyaW5nLFxuICAgIGN3ZD86IHN0cmluZ1xuICApOiBQcm9taXNlPHN0cmluZz4ge1xuICAgIGNvbnN0IHJlcSA9IHRoaXMubm9kZVJlcXVpcmUoKTtcbiAgICBjb25zdCBjcCA9IHJlcSgnY2hpbGRfcHJvY2VzcycpIGFzIHR5cGVvZiBpbXBvcnQoJ2NoaWxkX3Byb2Nlc3MnKTtcblxuICAgIHJldHVybiBhd2FpdCBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBjaGlsZCA9IGNwLnNwYXduKGNvbW1hbmQsIGFyZ3MsIHtcbiAgICAgICAgY3dkLFxuICAgICAgICBzaGVsbDogZmFsc2UsXG4gICAgICAgIGVudjogcHJvY2Vzcy5lbnZcbiAgICAgIH0pO1xuXG4gICAgICBsZXQgc3Rkb3V0ID0gJyc7XG4gICAgICBsZXQgc3RkZXJyID0gJyc7XG5cbiAgICAgIGNoaWxkLnN0ZG91dD8ub24oJ2RhdGEnLCAoZDogQnVmZmVyKSA9PiAoc3Rkb3V0ICs9IGQudG9TdHJpbmcoJ3V0ZjgnKSkpO1xuICAgICAgY2hpbGQuc3RkZXJyPy5vbignZGF0YScsIChkOiBCdWZmZXIpID0+IChzdGRlcnIgKz0gZC50b1N0cmluZygndXRmOCcpKSk7XG4gICAgICBjaGlsZC5vbignZXJyb3InLCAoZXJyOiBOb2RlSlMuRXJybm9FeGNlcHRpb24pID0+IHtcbiAgICAgICAgaWYgKGVycj8uY29kZSA9PT0gJ0VOT0VOVCcpIHtcbiAgICAgICAgICByZWplY3QobmV3IEVycm9yKGAke2NvbW1hbmR9IG5vdCBmb3VuZCAoRU5PRU5UKS4gQ2hlY2sgQ0xJIHBhdGggaW4gcGx1Z2luIHNldHRpbmdzLmApKTtcbiAgICAgICAgICByZXR1cm47XG4gICAgICAgIH1cbiAgICAgICAgcmVqZWN0KGVycik7XG4gICAgICB9KTtcbiAgICAgIGNoaWxkLm9uKCdjbG9zZScsIChjb2RlKSA9PiB7XG4gICAgICAgIGlmIChjb2RlID09PSAwKSByZXNvbHZlKHN0ZG91dC50cmltKCkpO1xuICAgICAgICBlbHNlIHJlamVjdChuZXcgRXJyb3IoYCR7Y29tbWFuZH0gZXhpdGVkICR7Y29kZX06ICR7c3RkZXJyIHx8IHN0ZG91dH1gKSk7XG4gICAgICB9KTtcblxuICAgICAgaWYgKHN0ZGluVGV4dCAmJiBjaGlsZC5zdGRpbikge1xuICAgICAgICBjaGlsZC5zdGRpbi53cml0ZShzdGRpblRleHQpO1xuICAgICAgfVxuICAgICAgY2hpbGQuc3RkaW4/LmVuZCgpO1xuICAgIH0pO1xuICB9XG5cbiAgcHJpdmF0ZSBub2RlUmVxdWlyZSgpIHtcbiAgICBjb25zdCByZXEgPSAod2luZG93IGFzIHVua25vd24gYXMgeyByZXF1aXJlPzogTm9kZVJlcXVpcmUgfSkucmVxdWlyZTtcbiAgICBpZiAoIXJlcSkge1xuICAgICAgdGhyb3cgbmV3IEVycm9yKCdOb2RlIHJlcXVpcmUoKSB1bmF2YWlsYWJsZS4gTG9jYWwgQ0xJIG1vZGUgbmVlZHMgZGVza3RvcCBPYnNpZGlhbi4nKTtcbiAgICB9XG4gICAgcmV0dXJuIHJlcTtcbiAgfVxuXG4gIHByaXZhdGUgZm9ybWF0RGF0ZShkOiBEYXRlKTogc3RyaW5nIHtcbiAgICByZXR1cm4gZC50b0lTT1N0cmluZygpLnNsaWNlKDAsIDEwKTtcbiAgfVxufVxuXG5jbGFzcyBCbGlwUmVzdXJmYWNlclNldHRpbmdUYWIgZXh0ZW5kcyBQbHVnaW5TZXR0aW5nVGFiIHtcbiAgcGx1Z2luOiBCbGlwUmVzdXJmYWNlclBsdWdpbjtcblxuICBjb25zdHJ1Y3RvcihhcHA6IEFwcCwgcGx1Z2luOiBCbGlwUmVzdXJmYWNlclBsdWdpbikge1xuICAgIHN1cGVyKGFwcCwgcGx1Z2luKTtcbiAgICB0aGlzLnBsdWdpbiA9IHBsdWdpbjtcbiAgfVxuXG4gIGRpc3BsYXkoKTogdm9pZCB7XG4gICAgY29uc3QgeyBjb250YWluZXJFbCB9ID0gdGhpcztcbiAgICBjb250YWluZXJFbC5lbXB0eSgpO1xuXG4gICAgY29udGFpbmVyRWwuY3JlYXRlRWwoJ2gyJywgeyB0ZXh0OiAnQmxpcCBSZXN1cmZhY2VyJyB9KTtcblxuICAgIG5ldyBTZXR0aW5nKGNvbnRhaW5lckVsKVxuICAgICAgLnNldE5hbWUoJ01heCBkYWlseSByZXN1cmZhY2VkIGJsaXBzJylcbiAgICAgIC5zZXREZXNjKCdIb3cgbWFueSBibGlwcyB0byB1cGRhdGUgaW4gb25lIHJ1bicpXG4gICAgICAuYWRkVGV4dCgodGV4dCkgPT5cbiAgICAgICAgdGV4dFxuICAgICAgICAgIC5zZXRWYWx1ZShTdHJpbmcodGhpcy5wbHVnaW4uc2V0dGluZ3MubWF4RGFpbHlSZXN1cmZhY2UpKVxuICAgICAgICAgIC5vbkNoYW5nZShhc3luYyAodmFsdWUpID0+IHtcbiAgICAgICAgICAgIGNvbnN0IG4gPSBOdW1iZXIodmFsdWUpO1xuICAgICAgICAgICAgaWYgKCFOdW1iZXIuaXNOYU4obikgJiYgbiA+IDApIHtcbiAgICAgICAgICAgICAgdGhpcy5wbHVnaW4uc2V0dGluZ3MubWF4RGFpbHlSZXN1cmZhY2UgPSBuO1xuICAgICAgICAgICAgICBhd2FpdCB0aGlzLnBsdWdpbi5zYXZlU2V0dGluZ3MoKTtcbiAgICAgICAgICAgIH1cbiAgICAgICAgICB9KVxuICAgICAgKTtcblxuICAgIG5ldyBTZXR0aW5nKGNvbnRhaW5lckVsKVxuICAgICAgLnNldE5hbWUoJ0FJIHByb3ZpZGVyJylcbiAgICAgIC5zZXREZXNjKCdVc2UgbG9jYWwgQ29kZXgvQ2xhdWRlIENMSSBieSBkZWZhdWx0IChubyBBUEkga2V5IG5lZWRlZCkuJylcbiAgICAgIC5hZGREcm9wZG93bigoZGQpID0+XG4gICAgICAgIGRkXG4gICAgICAgICAgLmFkZE9wdGlvbignbG9jYWwtY2xpJywgJ0xvY2FsIENMSSAoQ29kZXgvQ2xhdWRlKScpXG4gICAgICAgICAgLmFkZE9wdGlvbignb3BlbmFpJywgJ09wZW5BSSBBUEknKVxuICAgICAgICAgIC5hZGRPcHRpb24oJ2ZhbGxiYWNrJywgJ0ZhbGxiYWNrIG9ubHkgKHJ1bGVzKScpXG4gICAgICAgICAgLnNldFZhbHVlKHRoaXMucGx1Z2luLnNldHRpbmdzLmFpUHJvdmlkZXIpXG4gICAgICAgICAgLm9uQ2hhbmdlKGFzeW5jICh2YWx1ZTogQWlQcm92aWRlcikgPT4ge1xuICAgICAgICAgICAgdGhpcy5wbHVnaW4uc2V0dGluZ3MuYWlQcm92aWRlciA9IHZhbHVlO1xuICAgICAgICAgICAgYXdhaXQgdGhpcy5wbHVnaW4uc2F2ZVNldHRpbmdzKCk7XG4gICAgICAgICAgICB0aGlzLmRpc3BsYXkoKTtcbiAgICAgICAgICB9KVxuICAgICAgKTtcblxuICAgIGlmICh0aGlzLnBsdWdpbi5zZXR0aW5ncy5haVByb3ZpZGVyID09PSAnbG9jYWwtY2xpJykge1xuICAgICAgbmV3IFNldHRpbmcoY29udGFpbmVyRWwpXG4gICAgICAgIC5zZXROYW1lKCdMb2NhbCBDTEknKVxuICAgICAgICAuc2V0RGVzYygnU2VsZWN0IHdoaWNoIGluc3RhbGxlZCBDTEkgdG8gdXNlJylcbiAgICAgICAgLmFkZERyb3Bkb3duKChkZCkgPT5cbiAgICAgICAgICBkZFxuICAgICAgICAgICAgLmFkZE9wdGlvbignY29kZXgnLCAnQ29kZXgnKVxuICAgICAgICAgICAgLmFkZE9wdGlvbignY2xhdWRlJywgJ0NsYXVkZScpXG4gICAgICAgICAgICAuc2V0VmFsdWUodGhpcy5wbHVnaW4uc2V0dGluZ3MubG9jYWxDbGkpXG4gICAgICAgICAgICAub25DaGFuZ2UoYXN5bmMgKHZhbHVlOiBMb2NhbENsaSkgPT4ge1xuICAgICAgICAgICAgICB0aGlzLnBsdWdpbi5zZXR0aW5ncy5sb2NhbENsaSA9IHZhbHVlO1xuICAgICAgICAgICAgICBhd2FpdCB0aGlzLnBsdWdpbi5zYXZlU2V0dGluZ3MoKTtcbiAgICAgICAgICAgICAgdGhpcy5kaXNwbGF5KCk7XG4gICAgICAgICAgICB9KVxuICAgICAgICApO1xuXG4gICAgICBuZXcgU2V0dGluZyhjb250YWluZXJFbClcbiAgICAgICAgLnNldE5hbWUoJ1N0cmljdCBsb2NhbCBBSSBtb2RlJylcbiAgICAgICAgLnNldERlc2MoJ0lmIGxvY2FsIENMSSBmYWlscywgc3RvcCBydW4gaW5zdGVhZCBvZiBzaWxlbnRseSB1c2luZyBnZW5lcmljIGZhbGxiYWNrJylcbiAgICAgICAgLmFkZFRvZ2dsZSgodG9nZ2xlKSA9PlxuICAgICAgICAgIHRvZ2dsZVxuICAgICAgICAgICAgLnNldFZhbHVlKHRoaXMucGx1Z2luLnNldHRpbmdzLnN0cmljdExvY2FsQWkpXG4gICAgICAgICAgICAub25DaGFuZ2UoYXN5bmMgKHZhbHVlKSA9PiB7XG4gICAgICAgICAgICAgIHRoaXMucGx1Z2luLnNldHRpbmdzLnN0cmljdExvY2FsQWkgPSB2YWx1ZTtcbiAgICAgICAgICAgICAgYXdhaXQgdGhpcy5wbHVnaW4uc2F2ZVNldHRpbmdzKCk7XG4gICAgICAgICAgICB9KVxuICAgICAgICApO1xuXG4gICAgICBpZiAodGhpcy5wbHVnaW4uc2V0dGluZ3MubG9jYWxDbGkgPT09ICdjb2RleCcpIHtcbiAgICAgICAgbmV3IFNldHRpbmcoY29udGFpbmVyRWwpXG4gICAgICAgICAgLnNldE5hbWUoJ0NvZGV4IGJpbmFyeSBwYXRoJylcbiAgICAgICAgICAuc2V0RGVzYygnQWJzb2x1dGUgcGF0aCBwcmVmZXJyZWQgKGZpeGVzIEVOT0VOVCBvbiBzb21lIE9ic2lkaWFuIFBBVEggc2V0dXBzKScpXG4gICAgICAgICAgLmFkZFRleHQoKHRleHQpID0+XG4gICAgICAgICAgICB0ZXh0XG4gICAgICAgICAgICAgIC5zZXRQbGFjZWhvbGRlcignL1VzZXJzL3lvdS8ubnBtLWdsb2JhbC9iaW4vY29kZXgnKVxuICAgICAgICAgICAgICAuc2V0VmFsdWUodGhpcy5wbHVnaW4uc2V0dGluZ3MuY29kZXhQYXRoKVxuICAgICAgICAgICAgICAub25DaGFuZ2UoYXN5bmMgKHZhbHVlKSA9PiB7XG4gICAgICAgICAgICAgICAgdGhpcy5wbHVnaW4uc2V0dGluZ3MuY29kZXhQYXRoID0gdmFsdWUudHJpbSgpO1xuICAgICAgICAgICAgICAgIGF3YWl0IHRoaXMucGx1Z2luLnNhdmVTZXR0aW5ncygpO1xuICAgICAgICAgICAgICB9KVxuICAgICAgICAgICk7XG5cbiAgICAgICAgbmV3IFNldHRpbmcoY29udGFpbmVyRWwpXG4gICAgICAgICAgLnNldE5hbWUoJ05vZGUgYmluYXJ5IHBhdGggKGZvciBDb2RleCknKVxuICAgICAgICAgIC5zZXREZXNjKCdVc2VkIHRvIHJ1biBDb2RleCBKUyBlbnRyeXBvaW50IHdoZW4gZW52IFBBVEggaXMgbWlzc2luZyBub2RlJylcbiAgICAgICAgICAuYWRkVGV4dCgodGV4dCkgPT5cbiAgICAgICAgICAgIHRleHRcbiAgICAgICAgICAgICAgLnNldFBsYWNlaG9sZGVyKCcvb3B0L2hvbWVicmV3L2Jpbi9ub2RlJylcbiAgICAgICAgICAgICAgLnNldFZhbHVlKHRoaXMucGx1Z2luLnNldHRpbmdzLm5vZGVQYXRoKVxuICAgICAgICAgICAgICAub25DaGFuZ2UoYXN5bmMgKHZhbHVlKSA9PiB7XG4gICAgICAgICAgICAgICAgdGhpcy5wbHVnaW4uc2V0dGluZ3Mubm9kZVBhdGggPSB2YWx1ZS50cmltKCk7XG4gICAgICAgICAgICAgICAgYXdhaXQgdGhpcy5wbHVnaW4uc2F2ZVNldHRpbmdzKCk7XG4gICAgICAgICAgICAgIH0pXG4gICAgICAgICAgKTtcblxuICAgICAgICBuZXcgU2V0dGluZyhjb250YWluZXJFbClcbiAgICAgICAgICAuc2V0TmFtZSgnQ29kZXggbW9kZWwgKG9wdGlvbmFsKScpXG4gICAgICAgICAgLmFkZFRleHQoKHRleHQpID0+XG4gICAgICAgICAgICB0ZXh0XG4gICAgICAgICAgICAgIC5zZXRQbGFjZWhvbGRlcignZS5nLiBncHQtNS1jb2RleCcpXG4gICAgICAgICAgICAgIC5zZXRWYWx1ZSh0aGlzLnBsdWdpbi5zZXR0aW5ncy5jb2RleE1vZGVsKVxuICAgICAgICAgICAgICAub25DaGFuZ2UoYXN5bmMgKHZhbHVlKSA9PiB7XG4gICAgICAgICAgICAgICAgdGhpcy5wbHVnaW4uc2V0dGluZ3MuY29kZXhNb2RlbCA9IHZhbHVlLnRyaW0oKTtcbiAgICAgICAgICAgICAgICBhd2FpdCB0aGlzLnBsdWdpbi5zYXZlU2V0dGluZ3MoKTtcbiAgICAgICAgICAgICAgfSlcbiAgICAgICAgICApO1xuICAgICAgfSBlbHNlIHtcbiAgICAgICAgbmV3IFNldHRpbmcoY29udGFpbmVyRWwpXG4gICAgICAgICAgLnNldE5hbWUoJ0NsYXVkZSBiaW5hcnkgcGF0aCcpXG4gICAgICAgICAgLnNldERlc2MoJ0Fic29sdXRlIHBhdGggcHJlZmVycmVkIChmaXhlcyBFTk9FTlQgb24gc29tZSBPYnNpZGlhbiBQQVRIIHNldHVwcyknKVxuICAgICAgICAgIC5hZGRUZXh0KCh0ZXh0KSA9PlxuICAgICAgICAgICAgdGV4dFxuICAgICAgICAgICAgICAuc2V0UGxhY2Vob2xkZXIoJy9Vc2Vycy95b3UvLmxvY2FsL2Jpbi9jbGF1ZGUnKVxuICAgICAgICAgICAgICAuc2V0VmFsdWUodGhpcy5wbHVnaW4uc2V0dGluZ3MuY2xhdWRlUGF0aClcbiAgICAgICAgICAgICAgLm9uQ2hhbmdlKGFzeW5jICh2YWx1ZSkgPT4ge1xuICAgICAgICAgICAgICAgIHRoaXMucGx1Z2luLnNldHRpbmdzLmNsYXVkZVBhdGggPSB2YWx1ZS50cmltKCk7XG4gICAgICAgICAgICAgICAgYXdhaXQgdGhpcy5wbHVnaW4uc2F2ZVNldHRpbmdzKCk7XG4gICAgICAgICAgICAgIH0pXG4gICAgICAgICAgKTtcblxuICAgICAgICBuZXcgU2V0dGluZyhjb250YWluZXJFbClcbiAgICAgICAgICAuc2V0TmFtZSgnQ2xhdWRlIG1vZGVsIChvcHRpb25hbCknKVxuICAgICAgICAgIC5hZGRUZXh0KCh0ZXh0KSA9PlxuICAgICAgICAgICAgdGV4dFxuICAgICAgICAgICAgICAuc2V0UGxhY2Vob2xkZXIoJ2UuZy4gc29ubmV0JylcbiAgICAgICAgICAgICAgLnNldFZhbHVlKHRoaXMucGx1Z2luLnNldHRpbmdzLmNsYXVkZU1vZGVsKVxuICAgICAgICAgICAgICAub25DaGFuZ2UoYXN5bmMgKHZhbHVlKSA9PiB7XG4gICAgICAgICAgICAgICAgdGhpcy5wbHVnaW4uc2V0dGluZ3MuY2xhdWRlTW9kZWwgPSB2YWx1ZS50cmltKCk7XG4gICAgICAgICAgICAgICAgYXdhaXQgdGhpcy5wbHVnaW4uc2F2ZVNldHRpbmdzKCk7XG4gICAgICAgICAgICAgIH0pXG4gICAgICAgICAgKTtcbiAgICAgIH1cbiAgICB9XG5cbiAgICBpZiAodGhpcy5wbHVnaW4uc2V0dGluZ3MuYWlQcm92aWRlciA9PT0gJ29wZW5haScpIHtcbiAgICAgIG5ldyBTZXR0aW5nKGNvbnRhaW5lckVsKVxuICAgICAgICAuc2V0TmFtZSgnT3BlbkFJIEFQSSBrZXknKVxuICAgICAgICAuYWRkVGV4dCgodGV4dCkgPT5cbiAgICAgICAgICB0ZXh0XG4gICAgICAgICAgICAuc2V0UGxhY2Vob2xkZXIoJ3NrLS4uLicpXG4gICAgICAgICAgICAuc2V0VmFsdWUodGhpcy5wbHVnaW4uc2V0dGluZ3Mub3BlbmFpQXBpS2V5KVxuICAgICAgICAgICAgLm9uQ2hhbmdlKGFzeW5jICh2YWx1ZSkgPT4ge1xuICAgICAgICAgICAgICB0aGlzLnBsdWdpbi5zZXR0aW5ncy5vcGVuYWlBcGlLZXkgPSB2YWx1ZS50cmltKCk7XG4gICAgICAgICAgICAgIGF3YWl0IHRoaXMucGx1Z2luLnNhdmVTZXR0aW5ncygpO1xuICAgICAgICAgICAgfSlcbiAgICAgICAgKTtcblxuICAgICAgbmV3IFNldHRpbmcoY29udGFpbmVyRWwpXG4gICAgICAgIC5zZXROYW1lKCdPcGVuQUkgbW9kZWwnKVxuICAgICAgICAuYWRkVGV4dCgodGV4dCkgPT5cbiAgICAgICAgICB0ZXh0XG4gICAgICAgICAgICAuc2V0VmFsdWUodGhpcy5wbHVnaW4uc2V0dGluZ3Mub3BlbmFpTW9kZWwpXG4gICAgICAgICAgICAub25DaGFuZ2UoYXN5bmMgKHZhbHVlKSA9PiB7XG4gICAgICAgICAgICAgIHRoaXMucGx1Z2luLnNldHRpbmdzLm9wZW5haU1vZGVsID0gdmFsdWUudHJpbSgpIHx8ICdncHQtNG8tbWluaSc7XG4gICAgICAgICAgICAgIGF3YWl0IHRoaXMucGx1Z2luLnNhdmVTZXR0aW5ncygpO1xuICAgICAgICAgICAgfSlcbiAgICAgICAgKTtcbiAgICB9XG5cbiAgICBuZXcgU2V0dGluZyhjb250YWluZXJFbClcbiAgICAgIC5zZXROYW1lKCdVc2VyIGNvbnRleHQnKVxuICAgICAgLnNldERlc2MoJ1VzZWQgdG8gdGFpbG9yIG5leHQgcXVhbGl0eSBzdGVwcycpXG4gICAgICAuYWRkVGV4dEFyZWEoKHRleHQpID0+XG4gICAgICAgIHRleHRcbiAgICAgICAgICAuc2V0VmFsdWUodGhpcy5wbHVnaW4uc2V0dGluZ3MudXNlckNvbnRleHQpXG4gICAgICAgICAgLm9uQ2hhbmdlKGFzeW5jICh2YWx1ZSkgPT4ge1xuICAgICAgICAgICAgdGhpcy5wbHVnaW4uc2V0dGluZ3MudXNlckNvbnRleHQgPSB2YWx1ZTtcbiAgICAgICAgICAgIGF3YWl0IHRoaXMucGx1Z2luLnNhdmVTZXR0aW5ncygpO1xuICAgICAgICAgIH0pXG4gICAgICApO1xuXG4gICAgbmV3IFNldHRpbmcoY29udGFpbmVyRWwpXG4gICAgICAuc2V0TmFtZSgnUnVuIG5vdycpXG4gICAgICAuc2V0RGVzYygnTWFudWFsbHkgcmVzdXJmYWNlIGJsaXBzIGFuZCB1cGRhdGUgbm90ZXMgaW4tcGxhY2UnKVxuICAgICAgLmFkZEJ1dHRvbigoYnRuKSA9PlxuICAgICAgICBidG4uc2V0QnV0dG9uVGV4dCgnUmVzdXJmYWNlIG5vdycpLm9uQ2xpY2soYXN5bmMgKCkgPT4ge1xuICAgICAgICAgIGNvbnN0IGNvdW50ID0gYXdhaXQgdGhpcy5wbHVnaW4ucmVzdXJmYWNlTm93KCk7XG4gICAgICAgICAgbmV3IE5vdGljZShgQmxpcCBSZXN1cmZhY2VyOiB1cGRhdGVkICR7Y291bnR9IGJsaXAocylgKTtcbiAgICAgICAgfSlcbiAgICAgICk7XG4gIH1cbn1cbiJdLAogICJtYXBwaW5ncyI6ICI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBLHNCQVFPO0FBMEJQLElBQU0sbUJBQTJDO0FBQUEsRUFDL0MsbUJBQW1CO0FBQUEsRUFDbkIsWUFBWTtBQUFBLEVBQ1osVUFBVTtBQUFBLEVBQ1YsZUFBZTtBQUFBLEVBQ2YsWUFBWTtBQUFBLEVBQ1osYUFBYTtBQUFBLEVBQ2IsV0FBVztBQUFBLEVBQ1gsWUFBWTtBQUFBLEVBQ1osVUFBVTtBQUFBLEVBQ1YsY0FBYztBQUFBLEVBQ2QsYUFBYTtBQUFBLEVBQ2IsYUFDRTtBQUNKO0FBRUEsSUFBcUIsdUJBQXJCLGNBQWtELHVCQUFPO0FBQUEsRUFBekQ7QUFBQTtBQUNFLG9CQUFtQztBQUFBO0FBQUEsRUFFbkMsTUFBTSxTQUFTO0FBQ2IsVUFBTSxLQUFLLGFBQWE7QUFFeEIsU0FBSyxXQUFXO0FBQUEsTUFDZCxJQUFJO0FBQUEsTUFDSixNQUFNO0FBQUEsTUFDTixVQUFVLFlBQVk7QUFDcEIsY0FBTSxRQUFRLE1BQU0sS0FBSyxhQUFhO0FBQ3RDLFlBQUksdUJBQU8sNEJBQTRCLEtBQUssVUFBVTtBQUFBLE1BQ3hEO0FBQUEsSUFDRixDQUFDO0FBRUQsU0FBSyxXQUFXO0FBQUEsTUFDZCxJQUFJO0FBQUEsTUFDSixNQUFNO0FBQUEsTUFDTixVQUFVLFlBQVk7QUFDcEIsWUFBSTtBQUNGLGdCQUFNLE9BQU8sTUFBTSxLQUFLO0FBQUEsWUFDdEI7QUFBQSxZQUNBO0FBQUEsVUFDRjtBQUNBLGNBQUksdUJBQU8sZ0JBQWdCLEtBQUssU0FBUyxRQUFRLGVBQWUsS0FBSyxRQUFRLE1BQU0sR0FBRyxFQUFFLENBQUMsS0FBSztBQUFBLFFBQ2hHLFNBQVMsR0FBRztBQUNWLGNBQUksdUJBQU8sb0JBQW9CLEtBQUssU0FBUyxRQUFRLE1BQU0sT0FBUSxHQUFhLFdBQVcsQ0FBQyxFQUFFLE1BQU0sR0FBRyxHQUFHLENBQUMsRUFBRTtBQUFBLFFBQy9HO0FBQUEsTUFDRjtBQUFBLElBQ0YsQ0FBQztBQUVELFNBQUssY0FBYyxJQUFJLHlCQUF5QixLQUFLLEtBQUssSUFBSSxDQUFDO0FBQUEsRUFDakU7QUFBQSxFQUVBLE1BQU0sZUFBZTtBQUNuQixVQUFNLFNBQVMsT0FBTyxPQUFPLENBQUMsR0FBRyxrQkFBa0IsTUFBTSxLQUFLLFNBQVMsQ0FBQztBQUt4RSxRQUFJLE9BQU8sT0FBTyxjQUFjLFdBQVc7QUFDekMsVUFBSSxDQUFDLE9BQU8sVUFBVyxRQUFPLGFBQWE7QUFBQSxlQUNsQyxPQUFPLGVBQWUsV0FBWSxRQUFPLGFBQWE7QUFBQSxJQUNqRTtBQUdBLFFBQUksQ0FBQyxPQUFPLFlBQVksS0FBSyxLQUFLLE9BQU8sV0FBVyxTQUFTLGVBQWUsR0FBRztBQUM3RSxhQUFPLGFBQWE7QUFBQSxJQUN0QjtBQUNBLFFBQUksQ0FBQyxPQUFPLGFBQWEsS0FBSyxHQUFHO0FBQy9CLGFBQU8sY0FBYztBQUFBLElBQ3ZCO0FBQ0EsUUFBSSxDQUFDLE9BQU8sV0FBVyxLQUFLLEdBQUc7QUFDN0IsYUFBTyxZQUFZO0FBQUEsSUFDckI7QUFDQSxRQUFJLENBQUMsT0FBTyxZQUFZLEtBQUssR0FBRztBQUM5QixhQUFPLGFBQWE7QUFBQSxJQUN0QjtBQUNBLFFBQUksQ0FBQyxPQUFPLFVBQVUsS0FBSyxHQUFHO0FBQzVCLGFBQU8sV0FBVztBQUFBLElBQ3BCO0FBRUEsU0FBSyxXQUFXO0FBQUEsRUFDbEI7QUFBQSxFQUVBLE1BQU0sZUFBZTtBQUNuQixVQUFNLEtBQUssU0FBUyxLQUFLLFFBQVE7QUFBQSxFQUNuQztBQUFBLEVBRUEsTUFBTSxlQUFnQztBQUNwQyxVQUFNLFFBQVEsTUFBTSxLQUFLLGFBQWE7QUFDdEMsUUFBSSxDQUFDLE1BQU0sUUFBUTtBQUNqQixVQUFJLHVCQUFPLGlDQUFpQztBQUM1QyxhQUFPO0FBQUEsSUFDVDtBQUVBLFVBQU0sV0FBVyxNQUFNLE1BQU0sR0FBRyxLQUFLLElBQUksR0FBRyxLQUFLLFNBQVMsaUJBQWlCLENBQUM7QUFFNUUsZUFBVyxRQUFRLFVBQVU7QUFDM0IsWUFBTSxPQUFPLE1BQU0sS0FBSyxJQUFJLE1BQU0sS0FBSyxJQUFJO0FBQzNDLFlBQU0sT0FBTyxNQUFNLEtBQUssaUJBQWlCLEtBQUssVUFBVSxJQUFJO0FBQzVELFlBQU0sS0FBSyxpQkFBaUIsTUFBTSxJQUFJO0FBQUEsSUFDeEM7QUFFQSxXQUFPLFNBQVM7QUFBQSxFQUNsQjtBQUFBLEVBRUEsTUFBYyxlQUFpQztBQUM3QyxXQUFPLEtBQUssSUFBSSxNQUFNLGlCQUFpQixFQUNwQyxPQUFPLENBQUMsU0FBUztBQUNoQixZQUFNLFFBQVEsS0FBSyxJQUFJLGNBQWMsYUFBYSxJQUFJO0FBQ3RELFlBQU0sS0FBSyxPQUFPO0FBQ2xCLGFBQU8sTUFBTSxPQUFPLEdBQUcsUUFBUSxFQUFFLEVBQUUsWUFBWSxNQUFNO0FBQUEsSUFDdkQsQ0FBQyxFQUNBLEtBQUssQ0FBQyxHQUFHLE1BQU0sRUFBRSxLQUFLLFFBQVEsRUFBRSxLQUFLLEtBQUs7QUFBQSxFQUMvQztBQUFBLEVBRUEsTUFBYyxpQkFBaUIsTUFBYSxNQUFnQjtBQUMxRCxVQUFNLFVBQVUsS0FBSyxXQUFXLG9CQUFJLEtBQUssQ0FBQztBQUMxQyxVQUFNLGdCQUFnQjtBQUV0QixVQUFNLFFBQVE7QUFBQSxNQUNaLE9BQU8sT0FBTztBQUFBLE1BQ2QsbUJBQW1CLEtBQUssU0FBUyxlQUFlLGNBQWMsS0FBSyxTQUFTLFdBQVcsS0FBSyxTQUFTLFVBQVU7QUFBQSxNQUMvRyxjQUFjLEtBQUssT0FBTztBQUFBLE1BQzFCO0FBQUEsTUFDQSxHQUFHLEtBQUssVUFBVSxJQUFJLENBQUMsTUFBTSxPQUFPLENBQUMsRUFBRTtBQUFBLE1BQ3ZDLGVBQWUsS0FBSyxRQUFRO0FBQUEsTUFDNUI7QUFBQSxJQUNGLEVBQUUsS0FBSyxJQUFJO0FBRVgsVUFBTSxVQUFVLE1BQU0sS0FBSyxJQUFJLE1BQU0sS0FBSyxJQUFJO0FBRTlDLFFBQUksUUFBUSxTQUFTLGFBQWEsR0FBRztBQUNuQyxZQUFNLEtBQUssSUFBSSxNQUFNLE9BQU8sTUFBTSxHQUFHLFFBQVEsUUFBUSxDQUFDO0FBQUE7QUFBQSxFQUFPLEtBQUssRUFBRTtBQUNwRTtBQUFBLElBQ0Y7QUFFQSxVQUFNLFVBQVUsR0FBRyxRQUFRLFFBQVEsQ0FBQztBQUFBO0FBQUEsRUFBTyxhQUFhO0FBQUE7QUFBQSxFQUFPLEtBQUs7QUFDcEUsVUFBTSxLQUFLLElBQUksTUFBTSxPQUFPLE1BQU0sT0FBTztBQUFBLEVBQzNDO0FBQUEsRUFFQSxNQUFjLGlCQUFpQixPQUFlLGFBQXdDO0FBQ3BGLFFBQUksS0FBSyxTQUFTLGVBQWUsYUFBYTtBQUM1QyxVQUFJO0FBQ0YsZUFBTyxNQUFNLEtBQUssb0JBQW9CLE9BQU8sV0FBVztBQUFBLE1BQzFELFNBQVMsR0FBRztBQUNWLGNBQU0sTUFBTSxPQUFRLEdBQWEsV0FBVyxDQUFDO0FBQzdDLGdCQUFRLE1BQU0sb0NBQW9DLENBQUM7QUFDbkQsWUFBSSx1QkFBTywwQkFBMEIsS0FBSyxTQUFTLFFBQVEsWUFBWSxJQUFJLE1BQU0sR0FBRyxHQUFHLENBQUMsR0FBRztBQUMzRixZQUFJLEtBQUssU0FBUyxlQUFlO0FBQy9CLGdCQUFNO0FBQUEsUUFDUjtBQUFBLE1BQ0Y7QUFBQSxJQUNGO0FBRUEsUUFBSSxLQUFLLFNBQVMsZUFBZSxZQUFZLEtBQUssU0FBUyxhQUFhLEtBQUssR0FBRztBQUM5RSxVQUFJO0FBQ0YsZUFBTyxNQUFNLEtBQUssa0JBQWtCLE9BQU8sV0FBVztBQUFBLE1BQ3hELFNBQVMsR0FBRztBQUNWLGdCQUFRLE1BQU0saURBQWlELENBQUM7QUFBQSxNQUNsRTtBQUFBLElBQ0Y7QUFFQSxXQUFPLEtBQUssaUJBQWlCLE9BQU8sV0FBVztBQUFBLEVBQ2pEO0FBQUEsRUFFUSxZQUFZLE9BQWUsYUFBNkI7QUFDOUQsV0FBTztBQUFBO0FBQUE7QUFBQSxJQUdQLEtBQUssU0FBUyxXQUFXO0FBQUE7QUFBQTtBQUFBO0FBQUEsY0FJZixLQUFLO0FBQUE7QUFBQSxFQUVqQixZQUFZLE1BQU0sR0FBRyxJQUFJLENBQUM7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBLEVBUTFCO0FBQUEsRUFFQSxNQUFjLG9CQUFvQixPQUFlLGFBQXdDO0FBQ3ZGLFVBQU0sU0FBUyxLQUFLLFlBQVksT0FBTyxXQUFXO0FBQ2xELFVBQU0sWUFBWSxLQUFLLElBQUksTUFBTSxRQUFRLFlBQVk7QUFFckQsUUFBSSxTQUFTO0FBRWIsUUFBSSxLQUFLLFNBQVMsYUFBYSxTQUFTO0FBQ3RDLFlBQU0sTUFBTSxLQUFLLFlBQVk7QUFDN0IsWUFBTSxLQUFLLElBQUksSUFBSTtBQUNuQixZQUFNLEtBQUssSUFBSSxJQUFJO0FBQ25CLFlBQU0sT0FBTyxJQUFJLE1BQU07QUFDdkIsWUFBTSxXQUFXLEtBQUssc0JBQXNCLFNBQVMsS0FBSyxTQUFTLFNBQVM7QUFDNUUsWUFBTSxVQUFVLEtBQUssS0FBSyxHQUFHLE9BQU8sR0FBRyxtQkFBbUIsS0FBSyxJQUFJLENBQUMsT0FBTztBQUMzRSxZQUFNLGFBQWEsS0FBSyxLQUFLLEdBQUcsT0FBTyxHQUFHLDBCQUEwQixLQUFLLElBQUksQ0FBQyxPQUFPO0FBQ3JGLFNBQUc7QUFBQSxRQUNEO0FBQUEsUUFDQSxLQUFLLFVBQVU7QUFBQSxVQUNiLE1BQU07QUFBQSxVQUNOLHNCQUFzQjtBQUFBLFVBQ3RCLFVBQVUsQ0FBQyxXQUFXLGFBQWEsVUFBVTtBQUFBLFVBQzdDLFlBQVk7QUFBQSxZQUNWLFNBQVMsRUFBRSxNQUFNLFNBQVM7QUFBQSxZQUMxQixXQUFXLEVBQUUsTUFBTSxTQUFTLFVBQVUsR0FBRyxVQUFVLEdBQUcsT0FBTyxFQUFFLE1BQU0sU0FBUyxFQUFFO0FBQUEsWUFDaEYsVUFBVSxFQUFFLE1BQU0sU0FBUztBQUFBLFVBQzdCO0FBQUEsUUFDRixDQUFDO0FBQUEsTUFDSDtBQUVBLFlBQU0sT0FBTztBQUFBLFFBQ1g7QUFBQSxRQUNBO0FBQUEsUUFDQTtBQUFBLFFBQ0E7QUFBQSxRQUNBO0FBQUEsUUFDQTtBQUFBLFFBQ0E7QUFBQSxRQUNBO0FBQUEsUUFDQTtBQUFBLE1BQ0Y7QUFDQSxVQUFJLEtBQUssU0FBUyxXQUFXLEtBQUssR0FBRztBQUNuQyxhQUFLLE9BQU8sR0FBRyxHQUFHLFdBQVcsS0FBSyxTQUFTLFdBQVcsS0FBSyxDQUFDO0FBQUEsTUFDOUQ7QUFFQSxZQUFNLFVBQVUsS0FBSyxrQkFBa0IsS0FBSyxTQUFTLFFBQVE7QUFDN0QsWUFBTSxLQUFLLFdBQVcsU0FBUyxDQUFDLFVBQVUsR0FBRyxJQUFJLEdBQUcsUUFBUSxTQUFTO0FBQ3JFLGVBQVMsR0FBRyxXQUFXLE9BQU8sSUFBSSxHQUFHLGFBQWEsU0FBUyxNQUFNLElBQUk7QUFDckUsVUFBSSxHQUFHLFdBQVcsT0FBTyxFQUFHLElBQUcsV0FBVyxPQUFPO0FBQ2pELFVBQUksR0FBRyxXQUFXLFVBQVUsRUFBRyxJQUFHLFdBQVcsVUFBVTtBQUFBLElBQ3pELE9BQU87QUFDTCxZQUFNLFlBQVksS0FBSyxzQkFBc0IsVUFBVSxLQUFLLFNBQVMsVUFBVTtBQUMvRSxZQUFNLE9BQU8sQ0FBQyxNQUFNLG1CQUFtQixNQUFNO0FBQzdDLFVBQUksS0FBSyxTQUFTLFlBQVksS0FBSyxHQUFHO0FBQ3BDLGFBQUssS0FBSyxXQUFXLEtBQUssU0FBUyxZQUFZLEtBQUssQ0FBQztBQUFBLE1BQ3ZEO0FBQ0EsV0FBSyxLQUFLLE1BQU07QUFDaEIsZUFBUyxNQUFNLEtBQUssV0FBVyxXQUFXLE1BQU0sUUFBVyxTQUFTO0FBQUEsSUFDdEU7QUFFQSxXQUFPLEtBQUssa0JBQWtCLE1BQU07QUFBQSxFQUN0QztBQUFBLEVBRUEsTUFBYyxrQkFBa0IsT0FBZSxhQUF3QztBQUNyRixVQUFNLFNBQVMsS0FBSyxZQUFZLE9BQU8sV0FBVztBQUVsRCxVQUFNLE1BQU0sVUFBTSw0QkFBVztBQUFBLE1BQzNCLEtBQUs7QUFBQSxNQUNMLFFBQVE7QUFBQSxNQUNSLFNBQVM7QUFBQSxRQUNQLGVBQWUsVUFBVSxLQUFLLFNBQVMsWUFBWTtBQUFBLFFBQ25ELGdCQUFnQjtBQUFBLE1BQ2xCO0FBQUEsTUFDQSxNQUFNLEtBQUssVUFBVTtBQUFBLFFBQ25CLE9BQU8sS0FBSyxTQUFTO0FBQUEsUUFDckIsVUFBVSxDQUFDLEVBQUUsTUFBTSxRQUFRLFNBQVMsT0FBTyxDQUFDO0FBQUEsUUFDNUMsYUFBYTtBQUFBLFFBQ2IsaUJBQWlCLEVBQUUsTUFBTSxjQUFjO0FBQUEsTUFDekMsQ0FBQztBQUFBLElBQ0gsQ0FBQztBQUVELFVBQU0sTUFBTSxJQUFJLE1BQU0sVUFBVSxDQUFDLEdBQUcsU0FBUyxXQUFXO0FBQ3hELFdBQU8sS0FBSyxrQkFBa0IsR0FBRztBQUFBLEVBQ25DO0FBQUEsRUFFUSxrQkFBa0IsU0FBMkI7QUFDbkQsVUFBTSxNQUFNLFNBQVMsS0FBSyxLQUFLO0FBQy9CLFFBQUksU0FBNEIsQ0FBQztBQUVqQyxRQUFJO0FBQ0YsZUFBUyxLQUFLLE1BQU0sR0FBRztBQUFBLElBQ3pCLFFBQVE7QUFDTixZQUFNLFFBQVEsSUFBSSxRQUFRLEdBQUc7QUFDN0IsWUFBTSxPQUFPLElBQUksWUFBWSxHQUFHO0FBQ2hDLFVBQUksU0FBUyxLQUFLLE9BQU8sT0FBTztBQUM5QixZQUFJO0FBQ0YsbUJBQVMsS0FBSyxNQUFNLElBQUksTUFBTSxPQUFPLE9BQU8sQ0FBQyxDQUFDO0FBQUEsUUFDaEQsUUFBUTtBQUNOLG1CQUFTLENBQUM7QUFBQSxRQUNaO0FBQUEsTUFDRjtBQUFBLElBQ0Y7QUFFQSxXQUFPO0FBQUEsTUFDTCxTQUFTLE9BQU8sU0FBUyxLQUFLLEtBQUs7QUFBQSxNQUNuQyxXQUNFLE9BQU8sV0FBVyxPQUFPLE9BQU8sRUFBRSxNQUFNLEdBQUcsQ0FBQyxLQUFLO0FBQUEsUUFDL0M7QUFBQSxNQUNGO0FBQUEsTUFDRixVQUFVLE9BQU8sVUFBVSxLQUFLLEtBQUs7QUFBQSxJQUN2QztBQUFBLEVBQ0Y7QUFBQSxFQUVRLGlCQUFpQixPQUFlLGFBQStCO0FBQ3JFLFVBQU0sT0FBTyxHQUFHLEtBQUs7QUFBQSxFQUFLLFdBQVcsR0FBRyxZQUFZO0FBRXBELFFBQUksS0FBSyxTQUFTLE9BQU8sS0FBSyxLQUFLLFNBQVMsS0FBSyxLQUFLLEtBQUssU0FBUyxPQUFPLEdBQUc7QUFDNUUsYUFBTztBQUFBLFFBQ0wsU0FDRTtBQUFBLFFBQ0YsV0FBVztBQUFBLFVBQ1Q7QUFBQSxVQUNBO0FBQUEsVUFDQTtBQUFBLFFBQ0Y7QUFBQSxRQUNBLFVBQVU7QUFBQSxNQUNaO0FBQUEsSUFDRjtBQUVBLFFBQUksS0FBSyxTQUFTLFNBQVMsS0FBSyxLQUFLLFNBQVMsTUFBTSxLQUFLLEtBQUssU0FBUyxNQUFNLEtBQUssS0FBSyxTQUFTLE1BQU0sR0FBRztBQUN2RyxhQUFPO0FBQUEsUUFDTCxTQUNFO0FBQUEsUUFDRixXQUFXO0FBQUEsVUFDVDtBQUFBLFVBQ0E7QUFBQSxVQUNBO0FBQUEsUUFDRjtBQUFBLFFBQ0EsVUFBVTtBQUFBLE1BQ1o7QUFBQSxJQUNGO0FBRUEsV0FBTztBQUFBLE1BQ0wsU0FBUztBQUFBLE1BQ1QsV0FBVztBQUFBLFFBQ1Q7QUFBQSxRQUNBO0FBQUEsUUFDQTtBQUFBLE1BQ0Y7QUFBQSxNQUNBLFVBQVU7QUFBQSxJQUNaO0FBQUEsRUFDRjtBQUFBLEVBRVEsc0JBQXNCLE1BQWdCLGdCQUFnQztBQUM1RSxVQUFNLE1BQU0sS0FBSyxZQUFZO0FBQzdCLFVBQU0sS0FBSyxJQUFJLElBQUk7QUFDbkIsVUFBTSxPQUFPLElBQUksTUFBTTtBQUV2QixVQUFNLGFBQWE7QUFBQSxNQUNqQjtBQUFBLE1BQ0E7QUFBQSxNQUNBLEtBQUssS0FBSyxxQ0FBcUMsSUFBSTtBQUFBLE1BQ25ELEtBQUssS0FBSyxnQ0FBZ0MsSUFBSTtBQUFBLE1BQzlDLEtBQUssS0FBSyxRQUFRLElBQUksUUFBUSxJQUFJLG1CQUFtQixJQUFJO0FBQUEsTUFDekQsS0FBSyxLQUFLLFFBQVEsSUFBSSxRQUFRLElBQUksY0FBYyxJQUFJO0FBQUEsTUFDcEQscUJBQXFCLElBQUk7QUFBQSxNQUN6QixrQkFBa0IsSUFBSTtBQUFBLE1BQ3RCLFlBQVksSUFBSTtBQUFBLElBQ2xCLEVBQUUsT0FBTyxPQUFPO0FBRWhCLGVBQVcsS0FBSyxZQUFZO0FBQzFCLFVBQUksQ0FBQyxFQUFHO0FBQ1IsVUFBSSxNQUFNLEtBQU0sUUFBTztBQUN2QixVQUFJLEdBQUcsV0FBVyxDQUFDLEVBQUcsUUFBTztBQUFBLElBQy9CO0FBRUEsVUFBTSxJQUFJO0FBQUEsTUFDUixHQUFHLElBQUksbURBQW1ELFNBQVMsVUFBVSxVQUFVLFFBQVE7QUFBQSxJQUNqRztBQUFBLEVBQ0Y7QUFBQSxFQUVRLGtCQUFrQixnQkFBZ0M7QUFDeEQsVUFBTSxNQUFNLEtBQUssWUFBWTtBQUM3QixVQUFNLEtBQUssSUFBSSxJQUFJO0FBQ25CLFVBQU0sYUFBYSxDQUFDLGdCQUFnQiwwQkFBMEIsdUJBQXVCLE1BQU07QUFFM0YsZUFBVyxLQUFLLFlBQVk7QUFDMUIsVUFBSSxDQUFDLEVBQUc7QUFDUixVQUFJLE1BQU0sT0FBUSxRQUFPO0FBQ3pCLFVBQUksR0FBRyxXQUFXLENBQUMsRUFBRyxRQUFPO0FBQUEsSUFDL0I7QUFFQSxVQUFNLElBQUksTUFBTSxtRUFBbUU7QUFBQSxFQUNyRjtBQUFBLEVBRUEsTUFBYyxXQUNaLFNBQ0EsTUFDQSxXQUNBLEtBQ2lCO0FBQ2pCLFVBQU0sTUFBTSxLQUFLLFlBQVk7QUFDN0IsVUFBTSxLQUFLLElBQUksZUFBZTtBQUU5QixXQUFPLE1BQU0sSUFBSSxRQUFRLENBQUMsU0FBUyxXQUFXO0FBQzVDLFlBQU0sUUFBUSxHQUFHLE1BQU0sU0FBUyxNQUFNO0FBQUEsUUFDcEM7QUFBQSxRQUNBLE9BQU87QUFBQSxRQUNQLEtBQUssUUFBUTtBQUFBLE1BQ2YsQ0FBQztBQUVELFVBQUksU0FBUztBQUNiLFVBQUksU0FBUztBQUViLFlBQU0sUUFBUSxHQUFHLFFBQVEsQ0FBQyxNQUFlLFVBQVUsRUFBRSxTQUFTLE1BQU0sQ0FBRTtBQUN0RSxZQUFNLFFBQVEsR0FBRyxRQUFRLENBQUMsTUFBZSxVQUFVLEVBQUUsU0FBUyxNQUFNLENBQUU7QUFDdEUsWUFBTSxHQUFHLFNBQVMsQ0FBQyxRQUErQjtBQUNoRCxZQUFJLEtBQUssU0FBUyxVQUFVO0FBQzFCLGlCQUFPLElBQUksTUFBTSxHQUFHLE9BQU8seURBQXlELENBQUM7QUFDckY7QUFBQSxRQUNGO0FBQ0EsZUFBTyxHQUFHO0FBQUEsTUFDWixDQUFDO0FBQ0QsWUFBTSxHQUFHLFNBQVMsQ0FBQyxTQUFTO0FBQzFCLFlBQUksU0FBUyxFQUFHLFNBQVEsT0FBTyxLQUFLLENBQUM7QUFBQSxZQUNoQyxRQUFPLElBQUksTUFBTSxHQUFHLE9BQU8sV0FBVyxJQUFJLEtBQUssVUFBVSxNQUFNLEVBQUUsQ0FBQztBQUFBLE1BQ3pFLENBQUM7QUFFRCxVQUFJLGFBQWEsTUFBTSxPQUFPO0FBQzVCLGNBQU0sTUFBTSxNQUFNLFNBQVM7QUFBQSxNQUM3QjtBQUNBLFlBQU0sT0FBTyxJQUFJO0FBQUEsSUFDbkIsQ0FBQztBQUFBLEVBQ0g7QUFBQSxFQUVRLGNBQWM7QUFDcEIsVUFBTSxNQUFPLE9BQWdEO0FBQzdELFFBQUksQ0FBQyxLQUFLO0FBQ1IsWUFBTSxJQUFJLE1BQU0sb0VBQW9FO0FBQUEsSUFDdEY7QUFDQSxXQUFPO0FBQUEsRUFDVDtBQUFBLEVBRVEsV0FBVyxHQUFpQjtBQUNsQyxXQUFPLEVBQUUsWUFBWSxFQUFFLE1BQU0sR0FBRyxFQUFFO0FBQUEsRUFDcEM7QUFDRjtBQUVBLElBQU0sMkJBQU4sY0FBdUMsaUNBQWlCO0FBQUEsRUFHdEQsWUFBWSxLQUFVLFFBQThCO0FBQ2xELFVBQU0sS0FBSyxNQUFNO0FBQ2pCLFNBQUssU0FBUztBQUFBLEVBQ2hCO0FBQUEsRUFFQSxVQUFnQjtBQUNkLFVBQU0sRUFBRSxZQUFZLElBQUk7QUFDeEIsZ0JBQVksTUFBTTtBQUVsQixnQkFBWSxTQUFTLE1BQU0sRUFBRSxNQUFNLGtCQUFrQixDQUFDO0FBRXRELFFBQUksd0JBQVEsV0FBVyxFQUNwQixRQUFRLDRCQUE0QixFQUNwQyxRQUFRLHFDQUFxQyxFQUM3QztBQUFBLE1BQVEsQ0FBQyxTQUNSLEtBQ0csU0FBUyxPQUFPLEtBQUssT0FBTyxTQUFTLGlCQUFpQixDQUFDLEVBQ3ZELFNBQVMsT0FBTyxVQUFVO0FBQ3pCLGNBQU0sSUFBSSxPQUFPLEtBQUs7QUFDdEIsWUFBSSxDQUFDLE9BQU8sTUFBTSxDQUFDLEtBQUssSUFBSSxHQUFHO0FBQzdCLGVBQUssT0FBTyxTQUFTLG9CQUFvQjtBQUN6QyxnQkFBTSxLQUFLLE9BQU8sYUFBYTtBQUFBLFFBQ2pDO0FBQUEsTUFDRixDQUFDO0FBQUEsSUFDTDtBQUVGLFFBQUksd0JBQVEsV0FBVyxFQUNwQixRQUFRLGFBQWEsRUFDckIsUUFBUSw0REFBNEQsRUFDcEU7QUFBQSxNQUFZLENBQUMsT0FDWixHQUNHLFVBQVUsYUFBYSwwQkFBMEIsRUFDakQsVUFBVSxVQUFVLFlBQVksRUFDaEMsVUFBVSxZQUFZLHVCQUF1QixFQUM3QyxTQUFTLEtBQUssT0FBTyxTQUFTLFVBQVUsRUFDeEMsU0FBUyxPQUFPLFVBQXNCO0FBQ3JDLGFBQUssT0FBTyxTQUFTLGFBQWE7QUFDbEMsY0FBTSxLQUFLLE9BQU8sYUFBYTtBQUMvQixhQUFLLFFBQVE7QUFBQSxNQUNmLENBQUM7QUFBQSxJQUNMO0FBRUYsUUFBSSxLQUFLLE9BQU8sU0FBUyxlQUFlLGFBQWE7QUFDbkQsVUFBSSx3QkFBUSxXQUFXLEVBQ3BCLFFBQVEsV0FBVyxFQUNuQixRQUFRLG1DQUFtQyxFQUMzQztBQUFBLFFBQVksQ0FBQyxPQUNaLEdBQ0csVUFBVSxTQUFTLE9BQU8sRUFDMUIsVUFBVSxVQUFVLFFBQVEsRUFDNUIsU0FBUyxLQUFLLE9BQU8sU0FBUyxRQUFRLEVBQ3RDLFNBQVMsT0FBTyxVQUFvQjtBQUNuQyxlQUFLLE9BQU8sU0FBUyxXQUFXO0FBQ2hDLGdCQUFNLEtBQUssT0FBTyxhQUFhO0FBQy9CLGVBQUssUUFBUTtBQUFBLFFBQ2YsQ0FBQztBQUFBLE1BQ0w7QUFFRixVQUFJLHdCQUFRLFdBQVcsRUFDcEIsUUFBUSxzQkFBc0IsRUFDOUIsUUFBUSx5RUFBeUUsRUFDakY7QUFBQSxRQUFVLENBQUMsV0FDVixPQUNHLFNBQVMsS0FBSyxPQUFPLFNBQVMsYUFBYSxFQUMzQyxTQUFTLE9BQU8sVUFBVTtBQUN6QixlQUFLLE9BQU8sU0FBUyxnQkFBZ0I7QUFDckMsZ0JBQU0sS0FBSyxPQUFPLGFBQWE7QUFBQSxRQUNqQyxDQUFDO0FBQUEsTUFDTDtBQUVGLFVBQUksS0FBSyxPQUFPLFNBQVMsYUFBYSxTQUFTO0FBQzdDLFlBQUksd0JBQVEsV0FBVyxFQUNwQixRQUFRLG1CQUFtQixFQUMzQixRQUFRLHFFQUFxRSxFQUM3RTtBQUFBLFVBQVEsQ0FBQyxTQUNSLEtBQ0csZUFBZSxrQ0FBa0MsRUFDakQsU0FBUyxLQUFLLE9BQU8sU0FBUyxTQUFTLEVBQ3ZDLFNBQVMsT0FBTyxVQUFVO0FBQ3pCLGlCQUFLLE9BQU8sU0FBUyxZQUFZLE1BQU0sS0FBSztBQUM1QyxrQkFBTSxLQUFLLE9BQU8sYUFBYTtBQUFBLFVBQ2pDLENBQUM7QUFBQSxRQUNMO0FBRUYsWUFBSSx3QkFBUSxXQUFXLEVBQ3BCLFFBQVEsOEJBQThCLEVBQ3RDLFFBQVEsK0RBQStELEVBQ3ZFO0FBQUEsVUFBUSxDQUFDLFNBQ1IsS0FDRyxlQUFlLHdCQUF3QixFQUN2QyxTQUFTLEtBQUssT0FBTyxTQUFTLFFBQVEsRUFDdEMsU0FBUyxPQUFPLFVBQVU7QUFDekIsaUJBQUssT0FBTyxTQUFTLFdBQVcsTUFBTSxLQUFLO0FBQzNDLGtCQUFNLEtBQUssT0FBTyxhQUFhO0FBQUEsVUFDakMsQ0FBQztBQUFBLFFBQ0w7QUFFRixZQUFJLHdCQUFRLFdBQVcsRUFDcEIsUUFBUSx3QkFBd0IsRUFDaEM7QUFBQSxVQUFRLENBQUMsU0FDUixLQUNHLGVBQWUsa0JBQWtCLEVBQ2pDLFNBQVMsS0FBSyxPQUFPLFNBQVMsVUFBVSxFQUN4QyxTQUFTLE9BQU8sVUFBVTtBQUN6QixpQkFBSyxPQUFPLFNBQVMsYUFBYSxNQUFNLEtBQUs7QUFDN0Msa0JBQU0sS0FBSyxPQUFPLGFBQWE7QUFBQSxVQUNqQyxDQUFDO0FBQUEsUUFDTDtBQUFBLE1BQ0osT0FBTztBQUNMLFlBQUksd0JBQVEsV0FBVyxFQUNwQixRQUFRLG9CQUFvQixFQUM1QixRQUFRLHFFQUFxRSxFQUM3RTtBQUFBLFVBQVEsQ0FBQyxTQUNSLEtBQ0csZUFBZSw4QkFBOEIsRUFDN0MsU0FBUyxLQUFLLE9BQU8sU0FBUyxVQUFVLEVBQ3hDLFNBQVMsT0FBTyxVQUFVO0FBQ3pCLGlCQUFLLE9BQU8sU0FBUyxhQUFhLE1BQU0sS0FBSztBQUM3QyxrQkFBTSxLQUFLLE9BQU8sYUFBYTtBQUFBLFVBQ2pDLENBQUM7QUFBQSxRQUNMO0FBRUYsWUFBSSx3QkFBUSxXQUFXLEVBQ3BCLFFBQVEseUJBQXlCLEVBQ2pDO0FBQUEsVUFBUSxDQUFDLFNBQ1IsS0FDRyxlQUFlLGFBQWEsRUFDNUIsU0FBUyxLQUFLLE9BQU8sU0FBUyxXQUFXLEVBQ3pDLFNBQVMsT0FBTyxVQUFVO0FBQ3pCLGlCQUFLLE9BQU8sU0FBUyxjQUFjLE1BQU0sS0FBSztBQUM5QyxrQkFBTSxLQUFLLE9BQU8sYUFBYTtBQUFBLFVBQ2pDLENBQUM7QUFBQSxRQUNMO0FBQUEsTUFDSjtBQUFBLElBQ0Y7QUFFQSxRQUFJLEtBQUssT0FBTyxTQUFTLGVBQWUsVUFBVTtBQUNoRCxVQUFJLHdCQUFRLFdBQVcsRUFDcEIsUUFBUSxnQkFBZ0IsRUFDeEI7QUFBQSxRQUFRLENBQUMsU0FDUixLQUNHLGVBQWUsUUFBUSxFQUN2QixTQUFTLEtBQUssT0FBTyxTQUFTLFlBQVksRUFDMUMsU0FBUyxPQUFPLFVBQVU7QUFDekIsZUFBSyxPQUFPLFNBQVMsZUFBZSxNQUFNLEtBQUs7QUFDL0MsZ0JBQU0sS0FBSyxPQUFPLGFBQWE7QUFBQSxRQUNqQyxDQUFDO0FBQUEsTUFDTDtBQUVGLFVBQUksd0JBQVEsV0FBVyxFQUNwQixRQUFRLGNBQWMsRUFDdEI7QUFBQSxRQUFRLENBQUMsU0FDUixLQUNHLFNBQVMsS0FBSyxPQUFPLFNBQVMsV0FBVyxFQUN6QyxTQUFTLE9BQU8sVUFBVTtBQUN6QixlQUFLLE9BQU8sU0FBUyxjQUFjLE1BQU0sS0FBSyxLQUFLO0FBQ25ELGdCQUFNLEtBQUssT0FBTyxhQUFhO0FBQUEsUUFDakMsQ0FBQztBQUFBLE1BQ0w7QUFBQSxJQUNKO0FBRUEsUUFBSSx3QkFBUSxXQUFXLEVBQ3BCLFFBQVEsY0FBYyxFQUN0QixRQUFRLG1DQUFtQyxFQUMzQztBQUFBLE1BQVksQ0FBQyxTQUNaLEtBQ0csU0FBUyxLQUFLLE9BQU8sU0FBUyxXQUFXLEVBQ3pDLFNBQVMsT0FBTyxVQUFVO0FBQ3pCLGFBQUssT0FBTyxTQUFTLGNBQWM7QUFDbkMsY0FBTSxLQUFLLE9BQU8sYUFBYTtBQUFBLE1BQ2pDLENBQUM7QUFBQSxJQUNMO0FBRUYsUUFBSSx3QkFBUSxXQUFXLEVBQ3BCLFFBQVEsU0FBUyxFQUNqQixRQUFRLG9EQUFvRCxFQUM1RDtBQUFBLE1BQVUsQ0FBQyxRQUNWLElBQUksY0FBYyxlQUFlLEVBQUUsUUFBUSxZQUFZO0FBQ3JELGNBQU0sUUFBUSxNQUFNLEtBQUssT0FBTyxhQUFhO0FBQzdDLFlBQUksdUJBQU8sNEJBQTRCLEtBQUssVUFBVTtBQUFBLE1BQ3hELENBQUM7QUFBQSxJQUNIO0FBQUEsRUFDSjtBQUNGOyIsCiAgIm5hbWVzIjogW10KfQo=
